### ISSUE TITLE
[Bug] Crash whenever the notification button is pressed

### ISSUE THREAD

**Issue by pflo550** [qnblackcat/uYouPlus#45] opened 2022-01-20 02:25 UTC
**Device info:**
- iOS/iPadOS version: 15.2
- Device model: iPhone 12
- Sideload tool: AltStore
- Version of uYouPlus: 2.1

**Describe the bug:**
- Crash whenever the notification button is pressed, but only on a YouTube channel’s homepage.

**How to reproduce the bug:**
Go to any YouTube channel page and click the notification button.
Video attached: https://www.dropbox.com/s/xzq6lc1gf6visuf/IMG_6221.MOV?dl=0

**Crash log (if possible):**
https://www.dropbox.com/s/7qrvx021ha1f04o/YouTube-2022-01-19-211138.ips?dl=0

**Comment by qnblackcat** [comment] 2022-01-20 17:59
Duplicate of #15

**Closed by qnblackcat** 2022-01-20 17:59 UTC
Labels: bug
