### ISSUE TITLE
[Bug] App Crashes After Scrolling In Shorts

### ISSUE THREAD

**Issue by GizmoHD4Life** [qnblackcat/uYouPlus#391] opened 2022-08-18 20:28 UTC
### Device info
- iOS/iPadOS version: 16.4
- Device model: iPhone 12
- Sideload tool: Altstore
- Version of uYouPlus: 17.26.2

### Describe the bug

trying to scroll 3 times in the shorts section makes the app crash. 2 times is fine

### How to reproduce the bug

go to shorts

scroll 3 times

### Does the issue happen with the official YouTube from AppStore?

No

**Comment by GizmoHD4Life** [comment] 2022-08-18 20:30
seems to be the same as #253

**Comment by qnblackcat** [comment] 2022-08-19 00:32
Duplicate of #253

**Closed by qnblackcat** 2022-08-19 00:32 UTC
Labels: bug

**Comment by GizmoHD4Life** [comment] 2022-08-19 15:13
Dont Really Know If This Is New But Somebody mentioned that when using a sevond acc, the crash does not occur. for me however, it doesnt seem to work for me. 

also do you have any idea why this happens yet?
