### ISSUE TITLE
[Bug] Disable under player buttons

### ISSUE THREAD

**Issue by imloualvaro** [qnblackcat/uYouPlus#99] opened 2022-04-07 20:22 UTC
### Device info
- iOS/iPadOS version: iOS 15.4
- Device model: iphone 11
- Sideload tool: Appdb
- Version of uYouPlus: 17.2 — V2.1

### Description
It's not possible to disable cast on navigation/head bar, and same thing to buttons under player. I didn't get success to disable create, clip, download button.

**Comment by qnblackcat** [comment] 2022-04-08 04:15
Duplicate of  https://github.com/qnblackcat/uYouPlus/issues/41

**Closed by qnblackcat** 2022-04-08 04:16 UTC
Labels: bug
