### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bolognayballs** [qnblackcat/uYouPlus#146] opened 2022-05-07 16:35 UTC
It signs you out sometimes is it a bug or can it be fix

**Comment by qnblackcat** [comment] 2022-05-07 17:36
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/63

Next time you open an issue, please complete the issue template

**Closed by qnblackcat** 2022-05-07 17:36 UTC

**Comment by bolognayballs** [comment] 2022-05-07 17:38
Myissue doesn't have anything to do with #63
