### ISSUE TITLE
[Bug] Unable to reorder Create tab

### ISSUE THREAD

**Issue by oomek** [qnblackcat/uYouPlus#375] opened 2022-08-13 20:46 UTC
### Device info
- iOS/iPadOS version: 15.6
- Device model: Iphone 7 Plus
- Sideload tool: AltStore
- Version of uYouPlus: v17.31.4-2.1

### Describe the bug
Reordering Create tab has no effect. It always ends up last.

### How to reproduce the bug
![20220813_202123000_iOS](https://user-images.githubusercontent.com/2974860/184510234-b04153c5-dca6-42f0-a3df-d1c29a8dbe1b.jpg)

![20220813_202102000_iOS](https://user-images.githubusercontent.com/2974860/184510237-cf8207db-c704-476f-9d32-af5cb9163bc4.jpg)

### Does the issue happen with the official YouTube from AppStore?
Does not apply

**Comment by qnblackcat** [comment] 2022-08-14 00:07
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/107

**Closed by qnblackcat** 2022-08-14 00:07 UTC
Labels: bug
