### ISSUE TITLE
Immediately crashing on ios 16 dev 1

### ISSUE THREAD

**Issue by hardik007786** [qnblackcat/uYouPlus#199] opened 2022-06-10 03:41 UTC
It is newest vers 17.22.3_2.1.ipa
![0BB6C97A-680A-458A-A53A-B3A0D8C3C4CA](https://user-images.githubusercontent.com/100178548/172985714-381200e7-8fb1-4394-b201-2105bb63640f.png)

**Comment by qnblackcat** [comment] 2022-06-10 03:55
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/190

**Closed by qnblackcat** 2022-06-10 03:55 UTC
