### ISSUE TITLE
[Bug] all uYouPlus versions crash on launch with iOS 16 beta 1

### ISSUE THREAD

**Issue by iReadTOS** [qnblackcat/uYouPlus#195] opened 2022-06-07 22:54 UTC
### Device info
- iOS/iPadOS version: iOS 16.0b beta 1 (20a5283p)
- Device model: iPhone 13 Pro Max
- Sideload tool: AltStore
- Version of uYouPlus: was both 17.21.3-2.1 (original) and 17.22.3-2.1 (version I attempted to upgrade to)

### Describe the bug

Attempting to open uYouPlus on iOS 16 causes the app to crash during the splash screen, no matter which version I attempted to use. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

install iOS 16 beta 1, use AltStore to side load the uYouPlus app, attempt to open the app (after enabling developer mode), then watch app crash.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

{"app_name":"YouTube","timestamp":"2022-06-07 18:37:48.00 -0400","app_version":"17.22.3","slice_uuid":"57a7480d-c5aa-36b8-a916-7a43bc4cd2dd","build_version":"17.22.3","platform":2,"bundleID":"com.google.ios.youtube.6WUPK8P4H4","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.0 (20A5283p)","roots_installed":0,"name":"YouTube","incident_id":"4D76AF30-33C5-4657-A129-F60E064E6DC3"}
{
  "uptime" : 67000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone14,3",
  "coalitionID" : 1186,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.0",
    "releaseType" : "Beta",
    "build" : "20A5283p"
  },
  "captureTime" : "2022-06-07 18:37:47.2949 -0400",
  "incident" : "4D76AF30-33C5-4657-A129-F60E064E6DC3",
  "pid" : 3156,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-06-07 18:37:46.0014 -0400",
  "procStartAbsTime" : 1629371748902,
  "procExitAbsTime" : 1629402385882,
  "procName" : "YouTube",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/5E099C69-11A6-435E-BA2C-457CF37E9D54\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"17.22.3","CFBundleVersion":"17.22.3","CFBundleIdentifier":"com.google.ios.youtube.6WUPK8P4H4","DTAppStoreToolsBuild":"13F15"},
  "storeInfo" : {"deviceIdentifierForVendor":"2ABBC3F7-56B5-4394-B6EF-0C292AD1594D","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube.6WUPK8P4H4",
  "crashReporterKey" : "a5e2d48fd3fe4efaa4b59295d624286421406a68",
  "basebandVersion" : "2.04.00",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "ktriageinfo" : "VM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\n",
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "lastExceptionBacktrace" : [{"imageOffset":618696,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":5},{"imageOffset":94360,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":4},{"imageOffset":1559388,"symbol":"+[NSObject(NSObject) _copyDescription]","symbolLocation":0,"imageIndex":5},{"imageOffset":13722500,"symbol":"-[UIResponder doesNotRecognizeSelector:]","symbolLocation":260,"imageIndex":7},{"imageOffset":188432,"symbol":"___forwarding___","symbolLocation":1592,"imageIndex":5},{"imageOffset":184736,"symbol":"_CF_forwarding_prep_0","symbolLocation":96,"imageIndex":5},{"imageOffset":18674144,"imageIndex":15},{"imageOffset":1385636,"symbol":"-[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]","symbolLocation":84,"imageIndex":7},{"imageOffset":1394808,"symbol":"-[UIViewController loadViewIfRequired]","symbolLocation":792,"imageIndex":7},{"imageOffset":1245176,"symbol":"-[UIViewController view]","symbolLocation":24,"imageIndex":7},{"imageOffset":2786832,"symbol":"-[UIViewController _setPresentationController:]","symbolLocation":108,"imageIndex":7},{"imageOffset":3378840,"symbol":"-[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:]","symbolLocation":1072,"imageIndex":7},{"imageOffset":4017388,"symbol":"-[UIViewController _presentViewController:withAnimationController:completion:]","symbolLocation":3128,"imageIndex":7},{"imageOffset":2301356,"symbol":"__63-[UIViewController _presentViewController:animated:completion:]_block_invoke","symbolLocation":88,"imageIndex":7},{"imageOffset":1975220,"symbol":"-[UIViewController _performCoordinatedPresentOrDismiss:animated:]","symbolLocation":396,"imageIndex":7},{"imageOffset":3185980,"symbol":"-[UIViewController _presentViewController:animated:completion:]","symbolLocation":188,"imageIndex":7},{"imageOffset":2423060,"symbol":"-[UIViewController presentViewController:animated:completion:]","symbolLocation":164,"imageIndex":7},{"imageOffset":18898960,"imageIndex":15},{"imageOffset":19798460,"imageIndex":15},{"imageOffset":18755788,"imageIndex":15},{"imageOffset":18726688,"imageIndex":15},{"imageOffset":1385636,"symbol":"-[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]","symbolLocation":84,"imageIndex":7},{"imageOffset":1394808,"symbol":"-[UIViewController loadViewIfRequired]","symbolLocation":792,"imageIndex":7},{"imageOffset":2251324,"symbol":"-[UINavigationController _updateScrollViewFromViewController:toViewController:]","symbolLocation":124,"imageIndex":7},{"imageOffset":2239568,"symbol":"-[UINavigationController _startTransition:fromViewController:toViewController:]","symbolLocation":196,"imageIndex":7},{"imageOffset":4034380,"symbol":"-[UINavigationController _startDeferredTransitionIfNeeded:]","symbolLocation":608,"imageIndex":7},{"imageOffset":3071176,"symbol":"-[UINavigationController __viewWillLayoutSubviews]","symbolLocation":96,"imageIndex":7},{"imageOffset":2373764,"symbol":"-[UILayoutContainerView layoutSubviews]","symbolLocation":172,"imageIndex":7},{"imageOffset":1279360,"symbol":"-[UIView(CALayerDelegate) layoutSublayersOfLayer:]","symbolLocation":1980,"imageIndex":7},{"imageOffset":245660,"symbol":"CA::Layer::layout_if_needed(CA::Transaction*)","symbolLocation":500,"imageIndex":16},{"imageOffset":188088,"symbol":"CA::Layer::layout_and_display_if_needed(CA::Transaction*)","symbolLocation":148,"imageIndex":16},{"imageOffset":271444,"symbol":"CA::Context::commit_transaction(CA::Transaction*, double, double*)","symbolLocation":456,"imageIndex":16},{"imageOffset":309028,"symbol":"CA::Transaction::commit()","symbolLocation":652,"imageIndex":16},{"imageOffset":2788876,"symbol":"__34-[UIApplication _firstCommitBlock]_block_invoke_2","symbolLocation":36,"imageIndex":7},{"imageOffset":462268,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__","symbolLocation":28,"imageIndex":5},{"imageOffset":466080,"symbol":"__CFRunLoopDoBlocks","symbolLocation":368,"imageIndex":5},{"imageOffset":46132,"symbol":"__CFRunLoopRun","symbolLocation":856,"imageIndex":5},{"imageOffset":126892,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":4960,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":6},{"imageOffset":4240076,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":7},{"imageOffset":2170760,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":7},{"imageOffset":110820,"imageIndex":8},{"imageOffset":88432,"symbol":"start","symbolLocation":2352,"imageIndex":9}],
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":760937,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":7413354741},{"value":6159544512},{"value":110},{"value":0},{"value":17235074260270311807},{"value":17235074268184107839},{"value":512},{"value":11},{"value":11},{"value":0},{"value":0},{"value":7413354779},{"value":328},{"value":9537139264,"symbolLocation":0,"symbol":"_main_thread"},{"value":0},{"value":6},{"value":259},{"value":9537139488,"symbolLocation":224,"symbol":"_main_thread"},{"value":8532911728,"symbolLocation":0,"symbol":"__kCFAllocatorSystemDefault"},{"value":10783441952},{"value":1},{"value":1},{"value":1},{"value":0},{"value":6902754896,"symbolLocation":0,"symbol":"tlv_get_addr"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":8909239264},"cpsr":{"value":1073745920},"fp":{"value":6159544368},"sp":{"value":6159544336},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7964230272,"matchesCrashFrame":1},"far":{"value":8448156672}},"queue":"com.apple.main-thread","frames":[{"imageOffset":29312,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":29664,"symbol":"pthread_kill","symbolLocation":268,"imageIndex":1},{"imageOffset":134772,"symbol":"abort","symbolLocation":180,"imageIndex":2},{"imageOffset":72588,"symbol":"abort_message","symbolLocation":132,"imageIndex":3},{"imageOffset":6784,"symbol":"demangling_terminate_handler()","symbolLocation":336,"imageIndex":3},{"imageOffset":120252,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":4},{"imageOffset":69416,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":3},{"imageOffset":81612,"symbol":"__cxa_rethrow","symbolLocation":148,"imageIndex":3},{"imageOffset":102228,"symbol":"objc_exception_rethrow","symbolLocation":44,"imageIndex":4},{"imageOffset":127088,"symbol":"CFRunLoopRunSpecific","symbolLocation":808,"imageIndex":5},{"imageOffset":4960,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":6},{"imageOffset":4240076,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":7},{"imageOffset":2170760,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":7},{"imageOffset":110820,"imageIndex":8},{"imageOffset":88432,"symbol":"start","symbolLocation":2352,"imageIndex":9}]},{"id":760960,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":760961,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":760962,"queue":"com.apple.UIKit.KeyboardManagement","frames":[{"imageOffset":5888,"symbol":"__ulock_wait","symbolLocation":8,"imageIndex":0},{"imageOffset":19172,"symbol":"_dlock_wait","symbolLocation":56,"imageIndex":10},{"imageOffset":18584,"symbol":"_dispatch_thread_event_wait_slow","symbolLocation":56,"imageIndex":10},{"imageOffset":80152,"symbol":"__DISPATCH_WAIT_FOR_QUEUE__","symbolLocation":368,"imageIndex":10},{"imageOffset":79044,"symbol":"_dispatch_sync_f_slow","symbolLocation":144,"imageIndex":10},{"imageOffset":2871408,"symbol":"__37-[_UIRemoteKeyboards startConnection]_block_invoke_3","symbolLocation":156,"imageIndex":7},{"imageOffset":138932,"symbol":"__invoking___","symbolLocation":148,"imageIndex":5},{"imageOffset":259440,"symbol":"-[NSInvocation invoke]","symbolLocation":428,"imageIndex":5},{"imageOffset":194644,"symbol":"__NSXPCCONNECTION_IS_CALLING_OUT_TO_REPLY_BLOCK__","symbolLocation":16,"imageIndex":11},{"imageOffset":318924,"symbol":"-[NSXPCConnection _decodeAndInvokeReplyBlockWithEvent:sequence:replyInfo:]","symbolLocation":520,"imageIndex":11},{"imageOffset":7676196,"symbol":"__88-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]_block_invoke_5","symbolLocation":188,"imageIndex":11},{"imageOffset":120124,"symbol":"_xpc_connection_reply_callout","symbolLocation":124,"imageIndex":12},{"imageOffset":67380,"symbol":"_xpc_connection_call_reply_async","symbolLocation":88,"imageIndex":12},{"imageOffset":16756,"symbol":"_dispatch_client_callout3","symbolLocation":20,"imageIndex":10},{"imageOffset":139104,"symbol":"_dispatch_mach_msg_async_reply_invoke","symbolLocation":344,"imageIndex":10},{"imageOffset":46724,"symbol":"_dispatch_lane_serial_drain","symbolLocation":376,"imageIndex":10},{"imageOffset":49964,"symbol":"_dispatch_lane_invoke","symbolLocation":436,"imageIndex":10},{"imageOffset":93884,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":652,"imageIndex":10},{"imageOffset":4264,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":1},{"imageOffset":3656,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":1}]},{"id":760963,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":760964,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":760965,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":3016,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":77936,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":78512,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4364,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":29020,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":46508,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":126892,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":93380,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":11},{"imageOffset":333820,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":64,"imageIndex":11},{"imageOffset":3796788,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":436,"imageIndex":7},{"imageOffset":386728,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":11},{"imageOffset":6512,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":3668,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":760971,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":760972,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":760973,"name":"JavaScriptCore libpas scavenger","frames":[{"imageOffset":5276,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33440,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":993264,"symbol":"scavenger_thread_main","symbolLocation":1312,"imageIndex":13},{"imageOffset":6512,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":3668,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":760975,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":2908,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":18188,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":10},{"imageOffset":19724,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":10},{"imageOffset":88312,"symbol":"_dispatch_worker_thread","symbolLocation":324,"imageIndex":10},{"imageOffset":6512,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":3668,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":761030,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":3016,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":77936,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":78512,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4364,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":29020,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":46508,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":126892,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":2482576,"imageIndex":14},{"imageOffset":386728,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":11},{"imageOffset":6512,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":3668,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":761031,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":761032,"frames":[{"imageOffset":3648,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7964200960,
    "size" : 225260,
    "uuid" : "a0f02487-873e-35ad-83ed-03ea1f94c62e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8909209600,
    "size" : 49152,
    "uuid" : "0ec7fdb1-6969-3ff6-a4d6-b15e2ce9155c",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7178543104,
    "size" : 524276,
    "uuid" : "c2fb1f62-1ea2-3d69-a5a2-43806e8f02ae",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7413268480,
    "size" : 98300,
    "uuid" : "4276dce6-1ee7-32db-9b00-acb8cd9d13aa",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6902185984,
    "size" : 273888,
    "uuid" : "dbf26a3d-5f5a-3a32-9263-437606888add",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6905712640,
    "size" : 4067302,
    "uuid" : "32c2e1fb-f4d2-38bb-850e-eb60a917f8d8",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7481966592,
    "size" : 36864,
    "uuid" : "2614f5e3-500d-3916-97b0-68d0142862b8",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7021694976,
    "size" : 24555502,
    "uuid" : "400d16e6-cba0-31f9-8553-a7cf123855c3",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4307337216,
    "size" : 11583488,
    "uuid" : "57a7480d-c5aa-36b8-a916-7a43bc4cd2dd",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/5E099C69-11A6-435E-BA2C-457CF37E9D54\/YouTube.app\/YouTube",
    "name" : "YouTube"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 9354022912,
    "size" : 529960,
    "uuid" : "f307e43b-3c5c-3ead-9942-bc4fbc2d440f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6902460416,
    "size" : 290812,
    "uuid" : "f4202610-8403-3544-8686-977d40e3e999",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6918254592,
    "size" : 10809341,
    "uuid" : "94131410-ce48-3763-9446-448810fe9dc8",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8909320192,
    "size" : 262115,
    "uuid" : "c332d9dd-b4c8-3ffc-ad3e-c46843ccd546",
    "path" : "\/usr\/lib\/system\/libxpc.dylib",
    "name" : "libxpc.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7179419648,
    "size" : 21348342,
    "uuid" : "39fb66fd-9a21-38eb-b17b-8df373111f96",
    "path" : "\/System\/Library\/Frameworks\/JavaScriptCore.framework\/JavaScriptCore",
    "name" : "JavaScriptCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6913777664,
    "size" : 3993588,
    "uuid" : "15473d74-211b-3397-999c-bf7e0425ab91",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/CFNetwork",
    "name" : "CFNetwork"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4368089088,
    "size" : 27361280,
    "uuid" : "b8d1abdb-f036-348f-a8a6-e6e7b9657d74",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/5E099C69-11A6-435E-BA2C-457CF37E9D54\/YouTube.app\/Frameworks\/uYou.dylib",
    "name" : "uYou.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7046414336,
    "size" : 3481574,
    "uuid" : "8a9dcf85-4fc9-3485-8c72-3188da8d0595",
    "path" : "\/System\/Library\/Frameworks\/QuartzCore.framework\/QuartzCore",
    "name" : "QuartzCore"
  }
],
  "sharedCache" : {
  "base" : 6901432320,
  "size" : 3057582080,
  "uuid" : "5312bbb4-0e97-30b3-91d3-180899c597b0"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=806.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=806.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nCG raster data                     768K       22 \nColorSync                          432K       24 \nCoreAnimation                       16K        1 \nCoreData                           112K        3 \nCoreData Object IDs               4112K        2 \nCoreUI image data                 2640K       18 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           588.6M       94 \nMALLOC guard page                  192K       12 \nMach message                        16K        1 \nSQLite page cache                 1024K       16 \nSTACK GUARD                        224K       14 \nStack                             8080K       14 \nVM_ALLOCATE                        560K       10 \nWebKit Malloc                    192.1M        6 \n__AUTH                            3736K      541 \n__AUTH_CONST                      28.1M      723 \n__CTF                               756        1 \n__DATA                            55.2M      727 \n__DATA_CONST                      36.2M      733 \n__DATA_DIRTY                      3165K      609 \n__ETC                              112K        1 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       321.7M       17 \n__OBJC_CONST                      6841K      509 \n__OBJC_RO                         77.2M        1 \n__OBJC_RW                         2367K        1 \n__TEXT                           833.4M      752 \ndyld private memory                608K        4 \nlibnetwork                         640K       16 \nmapped file                      180.1M       43 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              2.3G     4924 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 250000156
    },
    {
      "rolloutId" : "6101c13693ebac18231ac9a1",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "629a51ceda9d33735ab475e1"
      },
      "deploymentId" : 250000327
    }
  ],
  "experiments" : [

  ]
}
}

### Additional context:

Enables developer mode and I tried all recent uYouPlus versions. Tried sideloadly and AltStore but none worked. Should also mention I looked at issue #190 but there were no solutions.

**Comment by arichorn** [comment] 2022-06-07 23:04
We know, we all got the issue, you aren’t the only one ;(

**Comment by qnblackcat** [comment] 2022-06-07 23:42
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/190

**Closed by qnblackcat** 2022-06-07 23:42 UTC
Labels: bug
