### ISSUE TITLE
[Bug] iOS 16 can’t download error 200

### ISSUE THREAD

**Issue by a100900900** [qnblackcat/uYouPlus#239] opened 2022-06-23 10:41 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16Beta
- Device model:iPhone 13 Pro
- Sideload tool：Esign
- Version of uYouPlus: 
[17.23.6-2.1-F2］[v17.24.4-2.1]

### Describe the bug
For Title
![](https://i.imgur.com/pXJdFj3.jpg)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by qnblackcat** [comment] 2022-06-23 11:07
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/238

**Closed by qnblackcat** 2022-06-23 11:07 UTC
Labels: bug
