### ISSUE TITLE
[Bug] Replace this with your title

### ISSUE THREAD

**Issue by eobi1976** [qnblackcat/uYouPlus#1186] opened 2023-07-11 22:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):

### Describe the bug

Whenever i click the cast button to play a YouTube video from uyouplus YouTube it doesn’t actually show the available devices like my smart tv which is available to cast in the normal YouTube app. Just wondering if there’s a fix for this 
Thanks 
/
![IMG_1035](https://github.com/qnblackcat/uYouPlus/assets/64454237/f8e77e88-d5ad-466b-b731-32b86bede8a6)
![IMG_1036](https://github.com/qnblackcat/uYouPlus/assets/64454237/b66c4be9-1d25-4c0d-96bd-76f71f26cb6c)

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment] 2023-09-03 16:08
duplicate of https://github.com/qnblackcat/uYouPlus/issues/1033

**Closed by qnblackcat** 2023-09-03 16:08 UTC
Labels: bug
