### ISSUE TITLE
[Bug] Cant download all videos from a playlist

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#20] opened 2021-12-11 21:13 UTC
**Device info:**
- iOS/iPadOS version: 15.2
- Device model: 12
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly
- Version of uYouPlus: latest

**Describe the bug:**
- at playlists there is the uYou button to download videos but it just says that it couldn't find any videos in that playlist. It doesnt matter which playlist I choose

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_
Press the button

**Additional context:**
_(Add any other context about the problem here)_

**Comment by qnblackcat** [comment] 2021-12-12 02:39
Duplicate of https://github.com/MiRO92/uYou-for-YouTube/issues/62

**Closed by qnblackcat** 2021-12-12 02:39 UTC
Labels: bug
