### ISSUE TITLE
[Bug] History won't save

### ISSUE THREAD

**Issue by skelbread** [qnblackcat/uYouPlus#127] opened 2022-04-26 02:20 UTC
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: iPhone 12 mini
- Sideload tool: Altstore
- Version of uYouPlus: 2.1

### Describe the bug

History doesn't save on my wifi. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

Watch video, check history, video doesn't appear, be mad. Pretty sure this only happens on my Wi-Fi though.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
Normal youtube works. In the past on my android, I've used vanced and I've run into the same problem, it was fixed for a while by using a Private DNS, but eventually the Private DNS stopped my network from working. My father is always doing crazy stuff for the Wi-Fi. Is there anything I should disable and test to see if it works?

**Comment by skelbread** [comment] 2022-04-26 02:39
update: doesnt work on normal youtube either :/

**Comment by skelbread** [comment] 2022-04-26 03:18
update: does work on normal youtube i lied

**Comment by qnblackcat** [comment] 2022-04-26 09:33
This is not an issue of uYouPlus. Just don’t mess up the DNS.
Also, duplicate of https://github.com/qnblackcat/uYouPlus/issues/117

**Closed by qnblackcat** 2022-04-26 09:33 UTC
Labels: bug
