### ISSUE TITLE
Cant sign in to google account because it is not "safe"

### ISSUE THREAD

**Issue by zejton** [qnblackcat/uYouPlus#314] opened 2022-07-28 07:14 UTC
Like the title says when i try to login into my google account i get this message
![IMG_AF3407B788C9-1](https://user-images.githubusercontent.com/40385994/181444141-e159e92b-03cd-4892-8f96-1cbf2bdbb2fa.jpeg)

You can't sign in to this app because Google can't
confirm that it's safe.

**Comment by qnblackcat** [comment] 2022-07-28 07:16
sorry about that. But it's not something I can fix

**Comment by qnblackcat** [comment] 2022-07-28 07:17
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/309

**Closed by qnblackcat** 2022-07-28 07:16 UTC

**Comment by zejton** [comment] 2022-07-28 07:36
alright thanks alot!

**Comment by misa198** [comment] 2022-07-28 08:02
I also had the same problem.

![0E2A0A96-0F84-4AF9-B388-701E1FF62BFC](https://user-images.githubusercontent.com/51451216/181453877-c49b1a47-5f37-4a1e-b151-025e7512209e.jpeg)
