### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bolognayballs** [qnblackcat/uYouPlus#399] opened 2022-08-20 19:47 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

### Additional context: 

Shorts bug
iOS 14.4.2
iPhone xs 
Sideloaded with signum.fun
Version 17.26.2 also happens on the latest version
When I watch shorts it crashes 
reproduce it keep scrolling shorts
Crash log
[YouTube-2022-08-20-213845 2.zip](https://github.com/qnblackcat/uYouPlus/files/9387936/YouTube-2022-08-20-213845.2.zip)
The log is in the zip and GitHub wasn’t letting me upload the log it self
>

**Comment by qnblackcat** [comment] 2022-08-21 01:07
Duplicate of #253

**Closed by qnblackcat** 2022-08-21 01:07 UTC
Labels: bug
