### ISSUE TITLE
[Bug] Cannot update app via altstore

### ISSUE THREAD

**Issue by anonymousaga** [qnblackcat/uYouPlus#756] opened 2022-12-12 04:54 UTC
Every update, when I tell altstore to install the newer version of the app, i get this error and cannot update:
https://imgur.com/a/sfDCafZ

I can't even uninstall and reinstall youtube; I have to completely uninstall altstore and reinstall it. Starting altstore from scratch is not a problem, but I have youtube fine-tuned to my liking and doing all the changes every time i update is tedious. I try to hold off updating, but cumulatively the features add up to a point where i really want to update. Should I post this as an issue in altstore as well? Thanks in advance.

**Comment by yodaluca23** [comment] 2022-12-12 12:27
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/360

Please read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) before creating a new issue.

Reason this happens can be found in qn's comment [here](https://github.com/qnblackcat/uYouPlus/issues/360#issuecomment-1214204795).

**Comment by anonymousaga** [comment] 2022-12-12 13:28
Thanks for this! I'll make sure to check the FAQ in the future!

**Closed** 2022-12-25 15:50 UTC
