### ISSUE TITLE
[Bug]CertubePlus 17.39.5 5.3.11 prerelease YouTube settings crashing

### ISSUE THREAD

**Issue by gototheskinny** [qnblackcat/uYouPlus#531] opened 2022-10-07 09:09 UTC
### Device info
- iOS/iPadOS version: 15.0
- Device model:iPhone 12
- Sideload tool TrollStore 1.1.2
- The specific version of uYouPlus: CertubePlus 17.39.5 5.3.11 prerelease (I couldn't open an issue on there so that's why I opened here)

### Describe the bug
When you try to open the YouTube settings app crashes.

### Does the issue happen with the official YouTube from AppStore?
No

### Additional context:

**Comment by qnblackcat** [comment] 2022-10-07 09:09
Duplicate of #530

**Closed by qnblackcat** 2022-10-07 09:09 UTC
Labels: bug

**Comment by gototheskinny** [comment] 2022-10-07 09:14
Sorry I didn't see.

**Comment by gototheskinny** [comment] 2022-10-07 09:23
Can you add YTSpeed to certubeplus? In uyouplus this feature is the best feature/tweak imo. I wanna switch to certube bc of the search tab ads issue of the uyou. I suppose I could add this tweak to the ipa with sideloady but I'm pretty sure other users could appreciate this too.
