### ISSUE TITLE
[Bug]  Can't download when signed with a developer license

### ISSUE THREAD

**Issue by thaibm1992** [qnblackcat/uYouPlus#835] opened 2022-12-31 05:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: Iphone 12 Pro Max
- Signed IPA by: 3utool and iOS App Signer
- The specific version of uYouPlus : 17.49.6
![Screenshot 2022-12-31 120229](https://user-images.githubusercontent.com/88101967/210125523-183aa2d1-40d3-4c9d-9944-24c71b36b680.png)

### Describe the bug

link review error: https://www.youtube.com/shorts/Olhow5KLTkU

![Screenshot 2022-12-31 120229](https://user-images.githubusercontent.com/88101967/210125524-665617e3-57f9-4fb7-97b9-9b828227b9d7.png)

### Steps to reproduce the issue

Sideloadly used normally only when signing with developer license will get this error

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

please help me a guide to fix it

thanks bro

**Comment by qnblackcat** [comment] 2022-12-31 05:21
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/238

**Closed by qnblackcat** 2022-12-31 05:21 UTC
Labels: bug
