### ISSUE TITLE
[Bug] Cannot turn on 'Remind me to take a break'

### ISSUE THREAD

**Issue by amit-bh** [qnblackcat/uYouPlus#55] opened 2022-02-07 16:38 UTC
**Device info:**
- iOS/iPadOS version: 15.3
- Device model: iPhone 11
- Sideload tool: AltStore
- Version of uYouPlus: 17.04.3

**Describe the bug:**
- Cannot turn on 'Remind me to take a break' feature on YouTube general settings. Turning it on causes the pop up to choose a time limit but after pressing ok, the feature turns off again. 

**How to reproduce the bug:**
Go to YouTube settings --> General. Try turning on 'Remind me to take a break' feature. 

**Crash log (if possible):**
N/A

**Additional context:**
N/A

**Comment by qnblackcat** [comment] 2022-02-07 16:47
yes. I can reproduce it. Can you try v16.42.3?

**Comment by amit-bh** [comment] 2022-02-08 00:21
> yes. I can reproduce it. Can you try v16.42.3?

Same issue with v16.42.3

**Comment by qnblackcat** [comment] 2022-04-15 19:14
@amit-bh Seems like disable blocing ads in uYou Settings fixed this bug. Can you try it? (uYou‘s settings > Other settings > Turn off Remove YouTube ads)

**Comment by amit-bh** [comment] 2022-04-15 19:38
> @amit-bh Seems like disable ads blocking in uYou Settings fixed this bug. Can you try it? (uYou‘s settings > Other settings > Turn off Remove YouTube ads)

Yea disabling ad block fixes the bug. Enabling again reintroduces the bug

**Comment by qnblackcat** [comment] 2022-04-15 19:51
Aright. uYouPlus blocks ads by default. There is no reason to enable blocking ads in uYou, as it unintendedly removes the timestamp in playlists, history, ...
Would you mind if I close the issue now?

**Comment by amit-bh** [comment] 2022-04-15 22:02
> Aright. uYouPlus blocks ads by default. There is no reason to enable blocking ads in uYou, as it unintendedly removes the timestamp in playlists, history, ...
> 
> Would you mind if I close the issue now?

Sounds good to me. I think good to close the issue now

Thanks for looking into it!

**Closed** 2022-04-16 00:01 UTC
Labels: bug
