### ISSUE TITLE
Can’t modify buttons below video player through uYou settings

### ISSUE THREAD

**Issue by oooooooooooooooo** [qnblackcat/uYouPlus#130] opened 2022-04-28 01:06 UTC
There’s a feature in the uYou settings to remove buttons like clips and create below the video player. But it doesn’t seem to be working. Not sure if this is related purely to uYou or if related to uYou+

I wasn’t able to find a fix to this issue or reports of it elsewhere from a short search.

The issue was present on 17.0.9.1 and is still present after upgrading to 17.1.6.4

My device is not jailbroken and is a 13 mini on iOS 15.4

**Comment by qnblackcat** [comment] 2022-04-28 01:58
Duplicate of #41

**Closed by qnblackcat** 2022-04-28 01:58 UTC
