### ISSUE TITLE
[Bug] Original youtube buttons under the video player (like, dislike, share, etc) aren't visible.

### ISSUE THREAD

**Issue by Klish132** [qnblackcat/uYouPlus#36] opened 2022-01-02 12:49 UTC
**Device info:**
- iOS/iPadOS version: IOS 15.2
- Device model: iPhone XR
- Sideload tool: AltStore
- Version of uYouPlus: v16.46.5-2.1

**Describe the bug:**
- Original youtube buttons under the video player (like, dislike, share, etc) aren't visible and don't work. Only the buttons added by uYou are visible.

**How to reproduce the bug:**
Restarting the app didn't help. Playing around with the "Buttons under the video player" settings also didn't help.
![mrRC_L_TnZ0](https://user-images.githubusercontent.com/43512312/147876115-0539f09e-3777-4432-af08-d2351d7af636.jpg)
![jaQMhRXyG30](https://user-images.githubusercontent.com/43512312/147876117-56aeb0cb-0894-4904-8e33-703454074c15.jpg)
![Qs1tFPP4YDc](https://user-images.githubusercontent.com/43512312/147876114-756a0703-957e-4f6d-b07e-7ffb1cd8c40a.jpg)

**Additional context:**
I also tried v16.42.3-2.1, but ran into the same problem, and additionally the "pause" button didn't work.

**Comment by qnblackcat** [comment] 2022-01-02 14:29
Weird. I’ve never seen anything like that, nor any report about it. I also can not reproduce the bug.

**Comment by Klish132** [comment] 2022-01-02 15:13
Could it be because I installed Cercube before downloading uYou+?

**Comment by qnblackcat** [comment] 2022-01-02 16:25
I don't think so. Have you tried to delete & reinstall the app?

**Comment by Klish132** [comment] 2022-01-02 18:07
Yes I've tried that, didn't help. Just installed using sideloadedly instead of altstore and the issue still persists.

**Comment by Klish132** [comment] 2022-01-02 18:18
Everything works fine on the previous release version (16.45.4_2.1)

**Comment by qnblackcat** [comment] 2022-01-03 01:36
Can you switch to another Youtube account?

**Comment by pcwizard7** [comment] 2022-01-03 05:03
There are too many buttons under the video to point the main up and down button are cut off and can’t be swipe to get to them.

also the official download button is redundant in this app
![Uploading 4211A205-EDF7-4760-BAA9-33B51EE7E3CA.jpeg…]()

**Comment by pcwizard7** [comment] 2022-01-03 05:06
![055EAF56-380C-4A46-8822-6E72B9B37685](https://user-images.githubusercontent.com/28586567/147900839-54268a03-c69f-45df-8f91-695444aafa55.jpeg)

**Comment by qnblackcat** [comment] 2022-01-03 05:10
> There are too many buttons under the video to point the main up and down button are cut off and can’t be swipe to get to them.
> 
> PS: I like to customise what buttons to show/hide buttons in the osd top of the video and under video
> 
> also the official download button is redundant in this app

Duplicate of https://github.com/qnblackcat/uYouPlus/issues/30

**Comment by Klish132** [comment] 2022-01-03 17:02
> Can you switch to another Youtube account?

Weird, I made a new google account, switched to it and the buttons appeared. Switched back to my main account and they were gone again.

**Comment by fastbreakj** [comment] 2022-01-03 20:33
I’m experiencing the same issue. iPhone 11 Pro Max iOS 15.1

**Comment by qnblackcat** [comment] 2022-01-03 23:43
> > Can you switch to another Youtube account?
> 
> Weird, I made a new google account, switched to it and the buttons appeared. Switched back to my main account and they were gone again.



> > Can you switch to another Youtube account?
> 
> Weird, I made a new google account, switched to it and the buttons appeared. Switched back to my main account and they were gone again.

I think YouTube enables A/B testing on your main account. We can’t do nothing about it unfortunately

@fastbreakj how about you? Have you tried a new account?

**Comment by Klish132** [comment] 2022-01-04 03:36
That's a shame. How come the previous release version works fine though?

**Comment by fastbreakj** [comment] 2022-01-04 08:05
> > > Can you switch to another Youtube account?
> > 
> > 
> > Weird, I made a new google account, switched to it and the buttons appeared. Switched back to my main account and they were gone again.
> 
> I think YouTube enables A/B testing on your main account. We can’t do nothing about it unfortunately
> 
> @fastbreakj how about you? Have you tried a new account?

Same for me. The buttons load properly on my alt account.

**Comment by qnblackcat** [comment] 2022-01-05 02:55
> That's a shame. How come the previous release version works fine though?

Newer YouTube version I think

**Comment by AngealAuditore** [comment] 2022-02-20 17:01
Help please why I can’t download videos or audio on uyou I get this error 
![Uploading 3484E9D8-013F-4202-AD1D-3796098FC3F2.png…]()

**Comment by AngealAuditore** [comment] 2022-02-20 17:05
![Uploading E797EDC0-CC85-4084-8D9E-799741F6B5F0.png…]()

**Comment by qnblackcat** [comment] 2022-04-19 08:18
Any update on this? @Klish132

**Comment by Klish132** [comment] 2022-04-19 16:26
> Any update on this? @Klish132

I haven't used the app since february because I was lazy. I'll install a new release and will get back to you.

**Comment by Klish132** [comment] 2022-04-19 17:21
Got the newest release (v17.15.1-2.1), the default youtube buttons are now visible, but the uYou buttons (uYou, uYouPiP, uYouLocal, etc) aren't. And they aren't set to be hidden in the settigsn. Everything else seems to work fine so i'm not complaining, wasn't using them anyway.

**Comment by qnblackcat** [comment] 2022-04-19 17:24
Aright. I‘ll close this issue then

**Closed by qnblackcat** 2022-04-19 17:24 UTC
Labels: bug
