### ISSUE TITLE
[Bug] Full Screen causing "Videos" tab to scroll down

### ISSUE THREAD

**Issue by LaeMat** [qnblackcat/uYouPlus#885] opened 2023-01-14 22:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.2
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!): v17.49.6-2.3~1

### Describe the bug

Here's a video of my problem:
https://streamable.com/jtuskc

### Steps to reproduce the issue

1. Go to "Videos" tab of a channel.
2. Tap on a video.
3. Enter full screen, exit full screen, and swipe back to the "Videos" tab view, and it should have scrolled down.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment] 2023-01-15 00:47
Lets me tell you how to reproduce this issue on vanilla YouTube: https://files.fm/u/hanwp3n6f
And no. This we won't fix

**Closed by qnblackcat** 2023-01-15 00:47 UTC
Labels: bug

**Comment by arichorn** [comment] 2023-01-15 02:13
> 1. Go to "Videos" tab of a channel.
> 2. Tap on a video.
> 3. Enter full screen, exit full screen, and swipe back to the "Videos" tab view, and it should have scrolled down.

Hey LaeMat. I think my way to fix the problem as a workaround is to downgrade to 16.42.3 of the app.
latest version of the app is bizarre, weird and buggy. Google literally has this definition of “if it’s not broken, don’t fix it” for a few years now.
and I haven’t had this issue happen to me on my iPad because of the version I’m using. 
if I’m wrong then ask qn can recommend you the stable versions of the yt app.

**Comment by LaeMat** [comment] 2023-01-15 03:46
> Lets me tell you how to reproduce this issue on vanilla YouTube: https://files.fm/u/hanwp3n6f
I tried this on vanilla YouTube and wasn't able to replicate it, weird.

**Comment by DmitriyMur** [comment] 2024-01-18 23:30
The issue can be replicated easily in official YouTube app, the key is to log in in YouTube, then force quit YouTube app, then launch it again (it applies many interface settings which are not applied during the first launch). This bug is still in the latest YouTube app version. The latest uYou+ without it is based on YouTube app version 17.43.1.

Newer versions are completely unusable for me because of this critical bug, would be great if someone fixed it somehow.

**Comment by yodaluca23** [comment] 2024-01-19 00:25
> it applies many interface settings which are not applied during the first launch.

It actually just applies the A/B flags for your account, meaning that if you're experiencing a bug that only happens after you force close it after logging in then that means it must be an issue with an AB flag it can be simply fixed by turning off a specific AB setting, now finding that setting good luck...

**Comment by DmitriyMur** [comment] 2024-01-19 19:38
Funny thing is, I couldn't even test whether this bug only happens if I log in to YouTube. Somehow YouTube app automatically logs me into my google account right after the first launch after installing the app, even after previously deleting all google apps from iPhone, clearing Safari history, cache, and manually deleting "site data" in Safari settings, deleting uYou+ and deleting google logins from iOS "Passwords". I have no idea where in iOS Google stores login information between reinstalls.

**Comment by DmitriyMur** [comment] 2024-02-07 01:25
I was so lucky that this damned setting starts with "c", close to the beginning of alphabet, so I found it relatively quickly by mass switching of all settings beginning with every letter and checking the bug. 

So, the damned A/B setting is called "channelsClientConfigIosChannelNavRestructuring" and you should DISABLE it to get rid of the bug. Problem solved! You can quickly find it by typing "Navrest" in A/B search field. All A/B settings, including this one, will be reset every time you uninstall and reinstall uYou+, so you'll need to do this after every install.

Yodaluca23, thank you for advice. 

![image](https://github.com/qnblackcat/uYouPlus/assets/157073311/f967d69b-98c6-45e9-a8f8-9952183ea895)
