### ISSUE TITLE
[v19.08.2-3.0.3] Crash When Trying To Open Any Video

### ISSUE THREAD

**Issue by NeHooYeY** [qnblackcat/uYouPlus#1361] opened 2024-03-15 15:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 15.4.1
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): TrollStore 

### Describe the issue

Today I noticed that I cannot open any video, app simply crashes.

### Steps to reproduce

1. Open YouTube
2. Tap On Any Video

### Crash log

```shell
{"crashreporter_key":"3b9f9166ca6223420a9ceb18034dc21f759516b3","bug_type":"211","timestamp":"2024-03-09 02:00:11.00 +0200","os_version":"iPhone OS 15.4.1 (19E258)","incident_id":"6A32EA97-00C8-42F8-831A-45A9FE2F5EFC"}
{"_marker":"<metadata>","_preferredUserInterfaceLanguage":"en-US","_userInterfaceLanguage":"en","_userSetRegionFormat":"US","basebandChipset":"ice18","basebandFirmwareVersion":"4.03.02","configParentUuid":"5367b217-82b8-42ca-bbf3-3c7d2fd2a829","configUuid":"aa58f4fd-4bfa-41a3-a89e-7a5a2c415787","currentCountry":"Israel","deviceCapacity":64,"homeCarrierCountry":"Israel","homeCarrierName":"Carrier IL","isDualSim":false,"rolloverReason":"scheduled","servingCarrierName":"Carrier IL","startTimestamp":"2024-03-08T00:00:13Z","trialExperiments":"0","trialRollouts":"2","version":"2.3"}
{"message":{"BogusFieldNotActuallyEverUsed":null,"Count":9,"daily_total_BogusMeasureNotActuallyEverUsed":null},"name":"StabilityHeartBeatCount5","sampling":100,"uuid":"3c8f638f-d492-465e-9e27-546a163beac9_3"}
{"message":{"Count":4,"Romeo_Fail_Status":0},"name":"RomeoFailStatusAggCountFullSampling","sampling":100,"uuid":"915b7fb3-11c4-42b1-8ae5-2bb13dcb9f08_2"}
{"_marker":"<end-of-file>"}
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by wundertuete** [comment] 2024-03-15 16:06
as of today the same is happening for me too

### Device information

     iOS version: 17.4
     Device model: iPhone 13
     Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Sideloadly

**Comment by practicalproblems23** [comment] 2024-03-15 16:22
It was happening to me also. I think it is an issue with iSponserBlock because it's fine after I disabled it.

**Comment by Sharpienero** [comment] 2024-03-15 16:39
Confirmed happening with me. 

https://github.com/qnblackcat/uYouPlus/issues/1361#issuecomment-2000011066 - confirmed this fixes the issue after disabling and restarting the app.

**Comment by wundertuete** [comment] 2024-03-15 16:42
> It was happening to me also. I think it is an issue with iSponserBlock because it's fine after I disabled it.

thanks after disabling and restarting the app i can watch videos again

**Comment by Cr4shMyCar** [comment] 2024-03-15 17:34
Can confirm this issue. iPhone 11 on IOS 17.3.1, using Altstore, same uYouPlus version as OP. Disabling iSponsorBlock fixed it.

**Comment by kuko872024** [comment] 2024-03-16 01:22
Iphone 11 & os 17.4 same case

**Comment by IamNickerson** [comment] 2024-03-17 04:35
Any fix for this

**Comment by maxexcloo** [comment] 2024-03-17 06:17
Having this issue also, thought this was fixed before?

**Comment by gmanc2** [comment] 2024-03-17 17:38
I can confirm. It is due to iSponsorBlock.

**Comment by enokseth** [comment] 2024-03-17 19:55
or if you see me I'm active on study of this projet and if you are using alstore and if this is the first time that you activate developer mode, the sidestore installation will have to be redone so that there are no conflicts between these activation steps

**Comment by IamNickerson** [comment] 2024-03-18 02:39
> I can confirm. It is due to iSponsorBlock.

Bro, we know it is sponsorblock

**Comment by ddalseong** [comment] 2024-03-27 02:05
I also turned off iSponsorBlock and that fixed the crash.

**Comment by sledgehammer617** [comment] 2024-03-28 03:38
It was working for me until just today, but turning off Sponsorblock fixes the issue.

**Comment by EgyptianComrade** [comment] 2024-03-28 15:28
Quick Fix :
1-Disable iSponsorBlock 
2-Open any video
3-Enable iSponsorBlock
4-Restart the app 
worked for me :>

**Comment by Wildtimo** [comment] 2024-03-29 04:50
It looks like the latest isponsorblock commit fixed this, we just have to wait for uyou to include it.

**Comment by Quickshadoww** [comment] 2024-03-30 15:18
> Quick Fix : 1-Disable iSponsorBlock 2-Open any video 3-Enable iSponsorBlock 4-Restart the app worked for me :>

nope, just disabling keep isponsorblock disabled doesnt crash it anymore

**Comment by enokseth** [comment] 2024-03-31 10:02
Disable sponsor block is the solution you can end this issue !

**Comment by Wildtimo** [comment] 2024-03-31 10:08
> Disable sponsor block is the solution you can end this issue !

Loosing a feature is not a solution it’s a work-around. I think it should stay open until sponsorblock is fixed.

**Comment by gmanc2** [comment] 2024-04-01 19:51
> It looks like the latest isponsorblock commit fixed this, we just have to wait for uyou to include it.

Hopefully relatively soon. It seems that Google may be attempting to shutdown anything similar Adblock. It's gonna be a rough time for YouTube and side-loaded apps for a while.

**Comment by timescam** [comment] 2024-04-02 01:28
Should be fixed, just rebuild uYouPlus. I tested it and it's working fine on my end.

**Comment by therealFoxster** [comment] 2024-04-07 18:29
Try my new build and lmk if it still crashes: https://therealfoxster.github.io/altsource-viewer/view/app/?source=https://therealfoxster.github.io/altsource/apps.json&id=com.google.ios.youtube#version-history

**Comment by therealFoxster** [comment] 2024-04-07 18:31
Try [this new build](https://therealfoxster.github.io/altsource-viewer/view/app/?source=https://therealfoxster.github.io/altsource/apps.json&id=com.google.ios.youtube#version-history) and lmk if it still crashes

**Comment by Wildtimo** [comment] 2024-04-07 19:46
I rebuilt and it seems to be fixed!

**Closed** 2024-04-10 03:32 UTC
Labels: bug
