### ISSUE TITLE
[Bug] app restores settings

### ISSUE THREAD

**Issue by chmohaa** [qnblackcat/uYouPlus#1168] opened 2023-06-28 04:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS 16.1.2
- Device model: iphone 11
- Sideload tool: esign with my certificate 
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):  18.14.1-3.0

### Describe the bug

after several visits in the application, all settings are reset, except for isponsorblock settings

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by elisaado** [comment] 2023-07-03 23:25
does it sign you out as well?

**Comment by chmohaa** [comment] 2023-07-04 10:11
> 

Yes, it is

**Comment by qnblackcat** [comment] 2023-09-03 16:01
duplicate of https://github.com/qnblackcat/uYouPlus/issues/335

**Closed by qnblackcat** 2023-09-03 16:01 UTC
Labels: bug
