### ISSUE TITLE
[Bug] Keep crashing on startup after download failed

### ISSUE THREAD

**Issue by AngeloAndreaIsola** [qnblackcat/uYouPlus#1118] opened 2023-05-10 07:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4.1.(a)
- Device model: Iphone X
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.14.1-3.0

### Describe the bug

On the first opening of the app it works fine, I can watch videos and all extensions work. 
The problem arise when I try do download a video. 
The download starts without any problems and goes for a bit, but if the screen lock the download will stop due to losing the connection. This will make it so that next time I will try to open the app the it will be just stuck on the youtube logo for a bit before crashing.

I have found also similar issues here:
https://github.com/MiRO92/uYou-for-YouTube/issues/270
https://github.com/qnblackcat/uYouPlus/issues/1107

But no solutions

### Steps to reproduce the issue

1. install 
2. open
3. download a video using uPlus downloads
4. lock screen during download
5. close the app
6. open again

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by lupus0802** [comment] 2023-05-12 04:59
You can see how to manually remove the malformed row here: [Issue 1107 - Comment](https://github.com/qnblackcat/uYouPlus/issues/1107#issuecomment-1545137756)
I hope this helps.

**Comment by qnblackcat** [comment] 2023-05-19 08:19
Duplicate of #1107

**Closed by qnblackcat** 2023-05-19 08:19 UTC
Labels: bug
