### ISSUE TITLE
[Bug] too many uYou Buttons below

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#248] opened 2022-06-28 02:23 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0 Developer Beta 2
- Device model: iPad Pro 10.5 Inch
- Sideload tool (Ex: AltStore, Sideloadly...) 
- Version of uYouPlus: v17.25.1-2.1 (my forked release)

### Describe the bug
Whenever I leave the app another uYou button multiplies with another button

### How to reproduce the bug
![969B85B9-0111-48B7-9B9B-1E8ACACC9DF8](https://user-images.githubusercontent.com/78001398/176077802-124d5061-57b1-4818-9aca-36cf52958782.jpeg)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:

**Comment by qnblackcat** [comment] 2022-06-28 02:24
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/30

**Closed by qnblackcat** 2022-06-28 02:24 UTC
Labels: bug

**Comment by arichorn** [comment] 2022-06-28 02:25
I didn’t know. Sorry
