### ISSUE TITLE
[Bug] Video quality and video player

### ISSUE THREAD

**Issue by LolekLiam** [qnblackcat/uYouPlus#1152] opened 2023-06-12 18:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.6
- Device model: iPad Pro (9.7-inch) A1673
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.14.1-3.0

### Describe the bug

Bug 1: When i click on a video, the video is smaller than the video player, the video needs to be put into fullscreen and back for the size to be normal.
Bug 2: When i change the quality on the video, it doesnt apply the quality provided. I repeat changing quality 2 or 3 times and then it works.

### Steps to reproduce the issue

BUG 1:
1. click on video
2. see this
![517943A3-58B6-4E3C-B2EF-60C75F18476E](https://github.com/qnblackcat/uYouPlus/assets/63475764/7ff15cc2-ca37-4286-adf3-c9cec818c290)

3. put on fullscreen and back to fix

BUG 2:
1. try to change quality
2. quality goes from for example auto 360p to advanced 360p
3. repeat 2 or 3 times till it finally works

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by LolekLiam** [comment] 2023-07-09 07:15
i fixed bug 2 by setting the video quality in uyou settings

**Comment by LolekLiam** [comment] 2023-07-09 07:16
bug 1 still happens

**Comment by LolekLiam** [comment] 2023-07-12 19:36
can someone please look into this?

**Comment by qnblackcat** [comment] 2023-09-03 16:44
duplicate of https://github.com/qnblackcat/uYouPlus/issues/736

**Closed by qnblackcat** 2023-09-03 16:44 UTC
Labels: bug

**Comment by myserverseven** [comment] 2024-06-08 22:15
Uyou plus 3.0.4 and prev versions dont work anymore on tvos. I airplay videos and it goes down always to the lowest quality even I have 2Gbps internet speed. Other apps are fine. I am not using it for the meantime and search for other options. I can't stand watching low quality video and audio
