### ISSUE TITLE
[Bug] Not able to view videos with suicide warning

### ISSUE THREAD

**Issue by lodesmets** [qnblackcat/uYouPlus#510] opened 2022-10-01 17:33 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.7
- Device model: Ipad 9th gen
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): altstore
- The specific version of uYouPlus: 17.37.3-2.1

### How to reproduce the bug
View this video: https://www.youtube.com/watch?v=JFJ5fF7cbE0  (this is a music video)
On pc it gives you a suicide warning, and asks you if you really want to view the video. But in this app it just says that "The following content may contain topics related to suicide or self-harm. Tap to retry". But tapping the video does nothing

### Crash log (if possible)
The app doesn't crash

### Are you using the newest version of uYouPlus? If not, why?
I updated to 17.37.3-2.1 (currently on 1-10-2022 the newest version) 

### Does the issue happen with the official YouTube from AppStore?
I don't have the official app on my ipad, but it works in youtube vanced on android.

### Additional context: 
Restricted mode is off (settings -> General -> restricted mode)

**Comment by qnblackcat** [comment] 2022-10-01 17:39
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by qnblackcat** [comment] 2022-10-01 17:40
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/349

**Closed by qnblackcat** 2022-10-01 17:39 UTC
Labels: bug

**Comment by lodesmets** [comment] 2022-10-01 17:41
I know this is a duplicate of issue. But my age restriction i already off
See attached image 
![IMG_0001](https://user-images.githubusercontent.com/31108717/193421569-9473bc05-1e4b-4d32-ae18-aaeb83c32981.PNG)

**Comment by lodesmets** [comment] 2022-10-01 17:45
I also tried to change the disable age restriction in uyou's settings

**Comment by qnblackcat** [comment] 2022-10-01 17:49
Turn off Disable Age Restriction in uYou's setting > Other settings

**Comment by pebble820** [comment] 2022-10-09 08:07
i cant find the option for other settings
