### ISSUE TITLE
Consolidate App Extensions to reduce App ID usage

### ISSUE THREAD

**Issue by WoodpeckerBaby** [qnblackcat/uYouPlus#39] opened 2022-01-05 11:55 UTC
Is it possible to consolidate App Extensions to reduce the number of App IDs used by the app?

When updating the app through AltStore, is it possible for it to use the same App IDs? Currently, I would have to delete the old app and wait for the App IDs to expire.

**Comment by qnblackcat** [comment] 2022-01-05 12:28
When updating the app, AltStore automatically uses the current app ID, it does not need a new app ID.

And no, you don't have to delete the old app, just connect AltStore to AltServer and resign the app.

**Comment by qnblackcat** [comment] 2022-01-05 12:28
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/38

**Closed by qnblackcat** 2022-01-05 12:28 UTC
Labels: question
