### ISSUE TITLE
Why am I seeing so many ads when searching?

### ISSUE THREAD

**Issue by WoodpeckerBaby** [qnblackcat/uYouPlus#622] opened 2022-10-28 21:17 UTC
### Device info
- iOS/iPadOS version: 16.1
- Device model: M2 iPad Pro 12.9, also on my iPhone 14 Pro Max
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.42.7-2.1

### Describe the bug
Ads, search ads everywhere 

### How to reproduce the bug
For example search some keywords that can lead to profitable ads like lawyers and divorce, or realtor. 

![image](https://user-images.githubusercontent.com/14303318/198733971-2b9a759d-45bd-40ca-a024-0b9bceefbbad.png)

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

I am. It takes a lot of effort upgrading every time because it fails to install 9/10 times. 

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

Obviously 

### Additional context:

**Comment by qnblackcat** [comment] 2022-10-29 00:11
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/622

**Closed by qnblackcat** 2022-10-29 00:11 UTC
Labels: bug
