### ISSUE TITLE
[Bug] Fail to load video with Viewer discretion advised

### ISSUE THREAD

**Issue by DelofJ** [qnblackcat/uYouPlus#448] opened 2022-09-11 22:11 UTC
### Device info
- iOS/iPadOS version: iOS 16
- Device model: iPhone 13 Pro
- Sideload tool: AltStore
- Version of uYouPlus: v17.33.2

### Describe the bug
On the vanilla YouTube, if you try to watch a video with "Viewer discretion is advised" you just click "Confirm" and everything is fine
![A97E3FCB-FF0F-41AF-9B84-E0F55BE1609B](https://user-images.githubusercontent.com/50058956/189550898-cf330e1c-1174-45e4-9e3c-78a52a842c38.jpeg)
But with uYouPlus, it instead show this error, and if you retry this keeps showing up
![475C9EE0-B0CF-4607-AB6F-4F4BE7FC55F4](https://user-images.githubusercontent.com/50058956/189550925-d7711bb3-19d0-4f06-bda3-da8575501abc.jpeg)

### How to reproduce the bug
- Launch a video with Viewer discretion advised, like this for example https://youtu.be/oJPvRvOFhYo
- See the error

### Crash log
No crash

### Does the issue happen with the official YouTube from AppStore?
No

**Comment by qnblackcat** [comment] 2022-09-13 00:51
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/25, https://github.com/qnblackcat/uYouPlus/issues/349

**Closed by qnblackcat** 2022-09-13 00:51 UTC
Labels: bug
