### ISSUE TITLE
[Bug] uYou Fullscreen to the Right persisting/remaining

### ISSUE THREAD

**Issue by CySxL** [qnblackcat/uYouPlus#657] opened 2022-11-07 07:33 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️
Yes, and also checked if there were same old issues posts before. Haven't found it.

### Device info
- iOS/iPadOS version: iOS 14.8/14.3
- Device model: iPhone 11 Pro Max/iPhone X
- Sideload tool: TrollStore 1.3.5
- The specific version of uYouPlus: v17.43.1-2.1

### Describe the bug
After using the overlay button of Fullscreen to the right once, I can't use the default fullscreen to the left feature anymore.

### How to reproduce the bug
1. Enable"uYou Fullscreen to The Right" toggle in "Video Controls Overlay" of uYou settings
2. Relaunch YouTube app 
3. Start playing a video
4. Tap on the default YouTube fullscreen button or swipe up on video to launch fullscreen
5. The fullscreen is in the left rotation now, which is the default rotation of YouTube
6. Leave fullscreen mode
7. Tap on the uYou Fullscreen to the right button
8. Video now rotates to the right fullscreen
9. Leave fullscreen mode again
10. Tap on the default YouTube fullscreen button or swipe up on video to launch fullscreen again
11. Video still rotates to the right fullscreen instead of the default left fullscreen mode
12. This issue persists throughout every videos after you use the uYou Fullscreen to the Right feature once, only relaunching YouTube app fixes it.
 
### Crash log (if possible)
No crash log produced.

### Are you using the newest version of uYouPlus? If not, why?
Yes,  v17.43.1-2.1 is the latest one at this moment.

### Does the issue happen with the official YouTube from AppStore?
Can't reproduce the issue since official YouTube app doesn't have the Fullscreen to the Right feature at all.

### Additional context: 
Thank you for your reading and your hard work ! Stay safe and healthy !!

**Comment by level3tjg** [comment] 2022-11-12 23:24
YouTube's button will set orientation to whatever it was the last time landscape was used, otherwise defaults to left. uYou's button turns right, YouTube remembers and will turn right as well. Sounds like intended behavior, if it would help maybe I can add a rotate left button?

**Comment by CySxL** [comment] 2022-11-13 04:40
> YouTube's button will set orientation to whatever it was the last time landscape was used, otherwise defaults to left. uYou's button turns right, YouTube remembers and will turn right as well. Sounds like intended behavior, if it would help maybe I can add a rotate left button?

That will be SUPER awesome !!! Thanks you a lot !! Please also make it standalone little tweak as I'm jailbroken and not using uYou Plus actually.

**Comment by level3tjg** [comment] 2022-11-13 21:09
Closing this as not planned because it seems too niche to add to uYouPlus. I made simple tweak to add a rotate left button for you anyways, deb is within the attached zip file

[com.level3tjg.uyoufullscreenleft.zip](https://github.com/qnblackcat/uYouPlus/files/9998224/com.level3tjg.uyoufullscreenleft.zip)

**Closed by level3tjg** 2022-11-13 21:09 UTC
Labels: bug

**Comment by CySxL** [comment] 2022-11-14 00:48
> Closing this as not planned because it seems too niche to add to uYouPlus. I made simple tweak to add a rotate left button for you anyways, deb is within the attached zip file
> 
> 
> 
> [com.level3tjg.uyoufullscreenleft.zip](https://github.com/qnblackcat/uYouPlus/files/9998224/com.level3tjg.uyoufullscreenleft.zip)
> 
> 

Thank you!!! It works perfectly!![image](https://user-images.githubusercontent.com/15531137/201554000-af5f4f6d-92f0-4b31-9a3f-bb6bcd92bab4.jpeg)

Do you plan to add it in your repo ? It'll be dope !!
