### ISSUE TITLE
[Bug] Brightness Gesture not working on ios 16.1.1

### ISSUE THREAD

**Issue by Donkalanka** [qnblackcat/uYouPlus#755] opened 2022-12-12 03:47 UTC
### Device info
- iOS/iPadOS version: 16.1.1
- Device model: 11 Pro Max
- Sideload tool: Sideloadly
- The specific version of uYouPlus: [v17.48.2-2.1]

### Describe the bug
The brightness gesture in videos doesn’t work
Seek and volume work but not brightness

### How to reproduce the bug
Go to uYou settings in uYou tab > Scroll to Gesture Control Settings > Change either to brightness and test
![9FC5F62F-6521-46FC-95BC-CFE4611181D5](https://user-images.githubusercontent.com/120352387/206956232-61d3e745-f0a0-422c-887a-aaeb8b37beb3.jpeg)
![0AD6B4AA-554C-49E5-83C3-14833D491383](https://user-images.githubusercontent.com/120352387/206956235-2a69c975-1de9-4d44-a9db-c33fee127a38.jpeg)

### Additional context: 
Could just be me
Worked on ios 15 but stopped working when I updated to ios 16

**Comment by qnblackcat** [comment] 2022-12-12 04:01
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/506

**Closed by qnblackcat** 2022-12-12 04:01 UTC
Labels: bug
