### ISSUE TITLE
[Bug] Disable Age Restriction doesn’t work

### ISSUE THREAD

**Issue by Manujito** [qnblackcat/uYouPlus#196] opened 2022-06-09 02:14 UTC
As title, still asks for verification on selected videos.

**Comment by qnblackcat** [comment] 2022-06-09 02:18
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/43

**Closed by qnblackcat** 2022-06-09 02:18 UTC
Labels: bug

**Comment by Manujito** [comment] 2022-06-09 02:31
Sorry didn’t notice, and I also searched for it was well.
