### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by bolognayballs** [qnblackcat/uYouPlus#392] opened 2022-08-18 23:29 UTC
Ios 14.4.2 iPhone XR shorts crash I thought it was the latest. Version that was crashing in but it’s happening in older versions too here’s the crash log 

> https://www.mediafire.com/file/0m7qlx1v7sestf1/YouTube-2022-08-19-011914.ips/file

**Comment by qnblackcat** [comment] 2022-08-19 00:32
Invalid and duplicate of #253

**Closed by qnblackcat** 2022-08-19 00:32 UTC
Labels: bug
