### ISSUE TITLE
[Bug] Very slow downloads

### ISSUE THREAD

**Issue by koningcool** [qnblackcat/uYouPlus#31] opened 2021-12-27 14:35 UTC
**Device info:**
- iOS/iPadOS version: 15.2
- Device model: iPhone 12
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: v16.45.4-2.1

**Describe the bug:**
- If i download a video, the download speed it very slow, like 40 kb per second
- ![402DD9C1-E747-4C72-9D70-AA9B3BE86BBE](https://user-images.githubusercontent.com/65183670/147481418-506c32b8-f168-439d-89aa-25d34ce07ce9.jpeg)

The video from above is not very long (5mb large) but with 1g video's the download speed is the same.

**How to reproduce the bug:**
-  Just download a video

**Comment by qnblackcat** [comment] 2021-12-29 16:25
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/2

It is a known issue. YouTube slows the download speed for 3rd party extensions. Let hope MiRO can fix it.

**Closed by qnblackcat** 2021-12-29 16:25 UTC
Labels: bug, duplicate
