### ISSUE TITLE
[Bug] Hide Previous and Next button doesn’t work with new versions of YT

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#338] opened 2022-08-04 20:26 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0 Public Beta 2
- Device model: iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore 
- Version of uYouPlus: 17.26.2 uYou+

### Describe the bug
YouTube has changed the UI on the video player and probably changed the code within the Next & Previous Buttons. Ever since YouTube changed it, it stopped making the option to hide the Previous & Next not to work anymore.

### How to reproduce the bug
![FCAE7444-060C-4944-A9DF-4807E46B9953](https://user-images.githubusercontent.com/78001398/182945940-fe27e60b-bc38-4761-b93e-b1229722535f.png)

### Does the issue happen with the official YouTube from AppStore?
This is from uYouPlus, YouTube from appstore is okay

### Additional context: 
I came here to let you know but I hope this helps! 🤞

**Comment by qnblackcat** [comment] 2022-08-04 23:49
Please update to v17.30.3-2.1

also duplicate of https://github.com/qnblackcat/uYouPlus/issues/308

**Closed by qnblackcat** 2022-08-04 23:49 UTC
Labels: bug

**Comment by arichorn** [comment] 2022-08-04 23:54
So sorry I didn’t know you made that version, it was in Pre-Release but glad that it was fixed
