### ISSUE TITLE
[Bug] New UI means Return Dislike no longer works

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#237] opened 2022-06-23 06:47 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.5
- Device model: SE 2020
- Sideload tool: AltStore
- Version of uYouPlus: Latest

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![image](https://user-images.githubusercontent.com/84964352/175233381-aceaf113-80a0-4a58-bda9-9e16d6287d32.png)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:

**Comment by qnblackcat** [comment] 2022-06-23 07:35
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/44

You can enable **Fake YouTube version** in YouPiP’s setting to get the old UI back

**Closed by qnblackcat** 2022-06-23 07:35 UTC
Labels: bug
