### ISSUE TITLE
Dislikes not in the right place

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#709] opened 2022-11-27 19:56 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️
yes

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.1.1
- Device model: iPhone SE 2020
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.43.1-2.1 

### Describe the bug
Dislikes are not in the right place, both likes and dislikes are in the "dislike" field

### How to reproduce the bug
click on a video

### Crash log (if possible)
x

### Are you using the newest version of uYouPlus? If not, why?
x

### Does the issue happen with the official YouTube from AppStore?
no they removed dislikes .-.

### Additional context: 
![IMG_3925](https://user-images.githubusercontent.com/80261988/204156593-dded47d1-12f9-433b-a707-8b23f68ce8e2.PNG)

**Comment by yodaluca23** [comment] 2022-11-27 20:00
https://github.com/PoomSmart/Return-YouTube-Dislikes/issues/35

**Comment by qnblackcat** [comment] 2022-11-27 23:50
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/635

**Closed by qnblackcat** 2022-11-27 23:50 UTC
Labels: bug
