### ISSUE TITLE
[Bug] Hidding buttons under video not working

### ISSUE THREAD

**Issue by Andy-Danderson** [qnblackcat/uYouPlus#41] opened 2022-01-11 00:42 UTC
**Device info:**
- iOS/iPadOS version: iOS 15.1
- Device model: iPhone Xʀ
- Sideload tool: AltStore
- Version of uYouPlus: 16.42.3_2.1

**Describe the bug:**
- The uYou settings that are meant to hide buttons underneath videos don't actually hide any of the buttons under the videos.

**How to reproduce the bug:**
Go to uYou settings. Underneath the section labeled "YT SETTINGS," procced to the subsection labeled "Buttons Under the Video Player." Turn on any of the switches that are meant to hide the buttons under the video player.

**Crash log (if possible):**
N/A

**Additional context:**
N/A

**Comment by qnblackcat** [comment] 2022-01-11 03:51
Duplicate of https://github.com/MiRO92/uYou-for-YouTube/issues/47

**Comment by pelegs29** [comment] 2022-01-23 23:10
Same thing is happening for me,
Device info:

iOS/iPadOS version: iOS 15.2.1
Device model: iPhone 12
Sideload tool: AltStore
Version of uYouPlus: 17.01.4_2.1

**Comment by Manujito** [comment] 2022-03-14 06:16
Same thing, can’t hide buttons under the video player.

17.09.01_2.1 sideloaded through AltStore

**Comment by PoomSmart** [comment] 2022-05-04 11:44
This is odd. They say 16.46.5 is the newest version that hiding those buttons still work.

https://www.reddit.com/r/jailbreak/comments/uh7ivp/question_i_know_uyou_has_these_options_but_they/

**Comment by qnblackcat** [comment] 2022-05-04 11:59
> This is odd. They say 16.46.5 is the newest version that hiding those buttons still work.
> 
> https://www.reddit.com/r/jailbreak/comments/uh7ivp/question_i_know_uyou_has_these_options_but_they/

Sadly, It does not work on jailed devices

**Comment by qnblackcat** [comment] 2023-04-15 02:14
This options will be removed in uYou 3.0

**Closed by qnblackcat** 2023-04-15 02:14 UTC
Labels: bug, uYou
