### ISSUE TITLE
[Bug] black bar

### ISSUE THREAD

**Issue by Epic0001** [qnblackcat/uYouPlus#719] opened 2022-11-28 23:23 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.1
- Device model:iPhone 13 pro
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) troll store
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ v17.43.1-2.1

### Describe the bug
Weird oled bars

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Screenshots below

![IMG_3121](https://user-images.githubusercontent.com/110989057/204402317-a4561819-bbdf-4b31-a97c-5f3e61511f7e.png)

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_no crash 

### Are you using the newest version of uYouPlus? If not, why? Yes
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No
### Additional context: 
Oled glitch thing when I turn on oled it makes shorts weird @
![E3B2CF31-67E9-4C36-A7CD-9D1EC00CB4EF](https://user-images.githubusercontent.com/110989057/204401682-2e2aa30e-aa47-4fb7-8f0b-226a7f103273.png)
![575CC547-06A8-42CC-953D-514C5B79B957](https://user-images.githubusercontent.com/110989057/204401688-5794cd18-d318-4f51-ab96-d0887b3838f6.png)

**Comment by Epic0001** [comment] 2022-11-29 01:26
Interestingly on this version it doesn’t happen.
![06BFF4E8-DF69-499E-BBB4-9A97DAF78E26](https://user-images.githubusercontent.com/110989057/204415692-2e372795-2a8f-47b2-9a5d-f3ced807c0c9.png)
![CCB75C5D-9218-49F9-AFA8-D8E665B1E93E](https://user-images.githubusercontent.com/110989057/204415700-a7a008ec-583c-4c4b-81cb-a7994fd357e9.png)

**Comment by Epic0001** [comment] 2022-11-29 01:39
Also on the newer version likes and dislikes are messed up they are both on the same button.

**Comment by arichorn** [comment] 2022-11-29 03:17
wtf, now that’s a new bug in shorts

**Comment by yodaluca23** [comment] 2022-11-29 03:57
> Also on the newer version likes and dislikes are messed up they are both on the same button.

https://github.com/PoomSmart/Return-YouTube-Dislikes/issues/35

**Comment by Epic0001** [comment] 2022-11-29 03:59
> > Also on the newer version likes and dislikes are messed up they are both on the same button.
> 
> [PoomSmart/Return-YouTube-Dislikes#35](https://github.com/PoomSmart/Return-YouTube-Dislikes/issues/35)

But still the black bar is bad

**Comment by arichorn** [comment] 2022-11-29 04:01
> wtf, now that’s a new bug in shorts

Also btw I was referring to the black bars in shorts, probably caused by OLED Dark Mode or uYou Incompatibility

**Comment by Epic0001** [comment] 2022-11-29 04:09
> > wtf, now that’s a new bug in shorts
> 
> Also btw I was referring to the black bars in shorts, probably caused by OLED Dark Mode or uYou Incompatibility

Yeah like I said if you turn off oled mode they go away.

**Comment by arichorn** [comment] 2022-11-29 04:41
Nah, I’m using an older version of YouTube so I don’t even have it.

**Comment by qnblackcat** [comment] 2022-12-12 02:35
Fixed in https://github.com/qnblackcat/uYouPlus/releases/tag/v17.48.2-2.1

**Closed by qnblackcat** 2022-12-12 02:35 UTC
Labels: bug
