### ISSUE TITLE
[Bug] Fullscreen To The Right completely inoperative in v18.07.5-2.3.1

### ISSUE THREAD

**Issue by tevyisertyin** [qnblackcat/uYouPlus#967] opened 2023-02-27 03:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.3.1
- Device model: iPhone XS Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly 0.40.0
- The specific version of uYouPlus (latest or newest is NOT a version number!): v18.07.5-2.3.1

### Describe the bug

This is NOT a duplicate of #453, where it was still possible to rotate the video to the right by pressing the button enough times.

Since v18.01.6-2.3.1, and now with 18.07.5-2.3.1, the "Fullscreen to the Right" function is completely inoperative. Pressing the on-screen button does not rotate the video at all, even when rotation lock is off.

### Steps to reproduce the issue

1. Launch uYouPlus
2. Make sure Video Controls Overlay > uYou Fullscreen to The Right is enabled
3. Restart uYouPlus
4. Watch any video
5. Press the Fullscreen to the right button.
6. Video plays in landscape mode to the left
7. Press the Fullscreen to the right button.
8. Video remains in landscape mode to the left.

### Crash log (if the app crashes)

The app does not crash, so no crash logs are generated.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore, because it does not have the "Fullscreen to the right" option

### Additional context

#900 reports the same problem for the previous release. This problem is still not fixed as of the current release.

**Comment by qnblackcat** [comment] 2023-02-27 03:44
Duplicate of #900

**Closed by qnblackcat** 2023-02-27 03:44 UTC
Labels: bug
