### ISSUE TITLE
Dislike counter is gone.

### ISSUE THREAD

**Issue by oomek** [qnblackcat/uYouPlus#393] opened 2022-08-20 07:30 UTC
### Device info
- iOS/iPadOS version: 15.6
- Device model: iPhone 7+
- Sideload tool: AltStore
- Version of uYouPlus:  latest

### Describe the bug
Dislike counter is no longer showing up.

### How to reproduce the bug
![D82638E0-F11B-4FCF-AD76-BFE502A6BFCB](https://user-images.githubusercontent.com/2974860/185734207-4b81c5c9-32f0-4cc4-ba4c-b44a316674a5.png)

**Comment by qnblackcat** [comment] 2022-08-20 07:53
“Latest” is not a version number

Also duplicate of https://github.com/qnblackcat/uYouPlus/issues/44

**Closed by qnblackcat** 2022-08-20 07:53 UTC
Labels: bug
