### ISSUE TITLE
[Bug] uYou download not working (Error 200)

### ISSUE THREAD

**Issue by thatkid662** [qnblackcat/uYouPlus#779] opened 2022-12-19 00:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

```markdown
- iOS/iPadOS version: 15.3.1
- Device model: iPad Air 2
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): Trollstore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ uYou v2.1
```

### Describe the bug

I download a video per normal and as the download finishes it comes up with error 200. I sideloaded it with Trollstore so it is not meant to happen but still does. I have searched the FAQ and issues but none of them are sideloaded with trollstore. Error: Unable to move file…

### Steps to reproduce the issue

1. Find a random video
2. Download it (uYou or uYou Local)
3. Wait for it to finish
4. Error!

### Are you using the newest version of uYouPlus? If not, why?

Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

No, It doesn't

### Additional context

Trollstore version v1.2.2

**Comment by qnblackcat** [comment] 2022-12-19 00:43
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/238

**Comment by thatkid662** [comment] 2022-12-19 00:43
But I’m on trollstore! That wasn’t on #238

**Closed by qnblackcat** 2022-12-19 00:43 UTC
Labels: bug
