### ISSUE TITLE
[Bug] uyou crashes while watching shorts 

### ISSUE THREAD

**Issue by rutvik788845** [qnblackcat/uYouPlus#377] opened 2022-08-15 06:19 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by rutvik788845** [comment] 2022-08-15 06:21
https://drive.google.com/open?id=19wCQ2BugOJxGHTTW4dlVm5umlINv6iGl&authuser=rp788845%40gmail.com&usp=drive_fs

**Comment by qnblackcat** [comment] 2022-08-15 07:06
Duplicate of #253

**Closed by qnblackcat** 2022-08-15 07:06 UTC
Labels: bug
