### ISSUE TITLE
Seeing Ads on the latest version of uyou plus

### ISSUE THREAD

**Issue by XxZETAPRIMExX** [qnblackcat/uYouPlus#1160] opened 2023-06-17 03:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.5
- Device model: iPad 9th Generation 
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.14.1 -3.0

### Describe the bug

I am seeing ads in the beginning of a video 
![IMG_1275](https://github.com/qnblackcat/uYouPlus/assets/136870199/f08f6742-ce64-47d8-a4a4-70f639a0c554)
on the latest version of uyouplus 

### Steps to reproduce the issue

1. I re downloaded it but still got same issue
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by 0xAndoroid** [comment] 2023-06-17 03:03
I'm seeing ads as well.

**Comment by XxZETAPRIMExX** [comment] 2023-06-17 03:06
> 
For me it started happening yesterday

**Comment by ctrlaltf44** [comment] 2023-06-17 04:39
Same started Happening to me yesterday. For some reason the “block ads” toggle in uyou keeps resetting each app restart

**Comment by XxZETAPRIMExX** [comment] 2023-06-17 06:11
> Same started Happening to me yesterday. For some reason the “block ads” toggle in uyou keeps resetting each app restart

Bro can you tell me how to to toggle block ads in uyou?

**Comment by Mukul1127** [comment] 2023-06-17 06:58
The Toggle in uYou is force disabled by uYouPlus to fix a bug, see FAQ

**Comment by XxZETAPRIMExX** [comment] 2023-06-17 07:02
> The Toggle in uYou is force disabled by uYouPlus to fix a bug, see FAQ

Ahh ok so I just have to wait until they fix the uyou plus ada bug because many other people are facing it aswell

**Comment by JakeAi** [comment] 2023-06-17 14:32
Never realized how bad the ads appear until they started appearing again… 😭

**Comment by drewbitt** [comment] 2023-06-18 03:06
> The Toggle in uYou is force disabled by uYouPlus to fix a bug, see FAQ

Yes, this was done 8 months ago, but it is not related to the toggle suddenly turning off in the last 24 hours for many of us. You could theorize a lot of people suddenly got it set to default for some reason.

**Comment by yodaluca23** [comment] 2023-06-18 03:18
I've been on the new YouTube version release, but the older uYou+ release, the one before latest, sense the latest one went back to let the OLED mode work, but mine works on the later version. Anyways, I don't have this problem at all, it's working fine for me, I don't have any ads at all. I'm going to [link my A/B config](https://pastebin.com/J74yBre7), in case that has anything to do with it.

**Comment by qnblackcat** [comment] 2023-06-19 08:15
Should be fixed in this commit by PoomSmart https://github.com/qnblackcat/uYouPlus/commit/61f8e79241983680f43917825bed136eda69c35e

**Comment by xbdmHQ** [comment] 2023-06-19 14:26
If you like to use invidious, check out my instance and has high security enhancement as well:

Blocks ads, trackers, etc
https://yt.whateveritworks.org/

Security:
WAF for attacks
Added Hide Invidious instance behind proxy server (for escaping DMCA requests)
Captcha for Login/Register to prevent spambots
Encryption at rest
Encryption in transit
Only Using TLS 1.2/TLS 1.3 (Harden enhancements, Perfect Forward Secrecy)
HSTS
QUIC
HMAC

Speed:
We use CDN to speed up video processing so you can watch your videos anywhere in the world without lag or slowdown.

High Uptime:
https://stats.uptimerobot.com/89VnzSKAn/794478524

**Comment by onepartsam** [comment] 2023-06-19 16:41
> Should be fixed in this commit by PoomSmart [61f8e79](https://github.com/qnblackcat/uYouPlus/commit/61f8e79241983680f43917825bed136eda69c35e)

Will there by a release soon? Or is there a guide that I can follow to build the IPA, I don't mind building it and sharing it.

**Comment by anoadragon453** [comment] 2023-06-19 18:37
> Should be fixed in this commit by PoomSmart [61f8e79](https://github.com/qnblackcat/uYouPlus/commit/61f8e79241983680f43917825bed136eda69c35e)

I had seen that commit but presumed it was unrelated. In the future, it would be helpful if some more context were included in commits.

If it was known that this commit fixed ads, it would have saved my friend - whom was unsure of when a fix would land - another month of a YouTube premium subscription.

**Comment by qnblackcat** [comment] 2023-06-20 03:51
> Will there by a release soon? Or is there a guide that I can follow to build the IPA, I don't mind building it and sharing it.

https://github.com/qnblackcat/uYouPlus/wiki/Building

**Comment by qnblackcat** [comment] 2023-06-20 03:51
> > Should be fixed in this commit by PoomSmart [61f8e79](https://github.com/qnblackcat/uYouPlus/commit/61f8e79241983680f43917825bed136eda69c35e)
> 
> Will there by a release soon? Or is there a guide that I can follow to build the IPA, I don't mind building it and sharing it.

https://github.com/qnblackcat/uYouPlus/wiki/Building

**Comment by Deeka0** [comment] 2023-06-20 08:23
> Somehow YouTube bypassed the app restrictions for the ads to make them appear, funny to see the amount of efforts from YouTube about ads

Exactly what I thought as well because the ads just appeared without an app update.

**Comment by 392Eleventh** [comment] 2023-06-20 20:08
not sure if this will work, but (so far) worked for me
go to A/B settings and disable "disableAfmaldfaCollection *"

search "afm" to find it more easily, so far no ads, will keep posted!

**Comment by BitEU** [comment] 2023-06-21 01:55
> not sure if this will work, but (so far) worked for me
> 
> go to A/B settings and disable "disableAfmaldfaCollection *"
> 
> 
> 
> search "afm" to find it more easily, so far no ads, will keep posted!

This worked for me

**Comment by 392Eleventh** [comment] 2023-06-21 02:39
> > not sure if this will work, but (so far) worked for me
> > go to A/B settings and disable "disableAfmaldfaCollection *"
> > search "afm" to find it more easily, so far no ads, will keep posted!
> 
> This worked for me

good to hear! I did re-enable it and the ads starting again, disabled it and then they completely stopped all together, even with the remove youtube ads option enabled in other settings, if this continues to work with others for prolonged time, might as well make a post about it haha

**Comment by lequan81** [comment] 2023-06-21 14:54
I have released a version to apply this [commit](https://github.com/qnblackcat/uYouPlus/commit/61f8e79241983680f43917825bed136eda69c35e) by PoomSmart. I hope this could help.

- [uYouPlus](https://github.com/lequan81/uYouPlus/releases/tag/v18.15.1-3.0) version 18.15.1 (tested, but have some problems with Oled UI)
- [uYouPlus](https://github.com/lequan81/uYouPlus/releases/tag/v18.15.1-3.0) version 18.12.2 (not test, but should work)

All releases have been done according to qnblackcat's [building instructions](https://github.com/qnblackcat/uYouPlus/wiki/Building)

**Comment by onepartsam** [comment] 2023-06-22 00:21
> I have released a version to apply this [commit](https://github.com/qnblackcat/uYouPlus/commit/61f8e79241983680f43917825bed136eda69c35e) by PoomSmart. I hope this could help.
> 
> * [uYouPlus](https://github.com/lequan81/uYouPlus/releases/tag/v18.15.1-3.0) version 18.15.1 (tested, but have some problems with Oled UI)
> * [uYouPlus](https://github.com/lequan81/uYouPlus/releases/tag/v18.12.2-3.0) version 18.12.2 (not tested, but should work)
> 
> All releases have been done according to qnblackcat's [building instructions](https://github.com/qnblackcat/uYouPlus/wiki/Building)

If y'all want one that is based on Youtube 18.23.3, tested to be working:
https://github.com/onepartsam/uYouPlus/releases/tag/v18.23.3-3.0-(1)

**Comment by JakeAi** [comment] 2023-06-23 01:51
> > I have released a version to apply this [commit](https://github.com/qnblackcat/uYouPlus/commit/61f8e79241983680f43917825bed136eda69c35e) by PoomSmart. I hope this could help.
> > 
> > * [uYouPlus](https://github.com/lequan81/uYouPlus/releases/tag/v18.15.1-3.0) version 18.15.1 (tested, but have some problems with Oled UI)
> > * [uYouPlus](https://github.com/lequan81/uYouPlus/releases/tag/v18.12.2-3.0) version 18.12.2 (not tested, but should work)
> > 
> > All releases have been done according to qnblackcat's [building instructions](https://github.com/qnblackcat/uYouPlus/wiki/Building)
> 
> If y'all want one that is based on Youtube 18.23.3, tested to be working: https://github.com/onepartsam/uYouPlus/releases/tag/v18.23.3-3.0-(1)

Your build crashes instantly when any video starts playing.

**Comment by yodaluca23** [comment] 2023-06-23 17:38
Here y'all go, latest YouTube release, with latest commit of uYou+ now use this, wait for a new offical release,or both.

https://github.com/yodaluca23/uYouPlus/releases/download/v18.23.3-3.0-(2)/uYouPlus_18.23.3_3.0.ipa

**Comment by JakeAi** [comment] 2023-06-23 17:49
> Here y'all go, latest YouTube release, with latest commit of uYou+ now use this, wait for a new offical release,or both.
> 
> https://github.com/yodaluca23/uYouPlus/releases/latest

Crashes when any video starts playing.

**Comment by JakeAi** [comment] 2023-06-23 17:58
> > Here y'all go, latest YouTube release, with latest commit of uYou+ now use this, wait for a new offical release,or both.
> > https://github.com/yodaluca23/uYouPlus/releases/latest
> 
> Crashes when any video starts playing.

deleting app first seems to work.

**Comment by JakeAi** [comment] 2023-06-23 18:37
> > > Here y'all go, latest YouTube release, with latest commit of uYou+ now use this, wait for a new offical release,or both.
> > > https://github.com/yodaluca23/uYouPlus/releases/latest
> > 
> > 
> > Crashes when any video starts playing.
> 
> deleting app first seems to work.

If you change settings in uYou,  it crashes the app.

**Comment by yodaluca23** [comment] 2023-06-23 18:58
> If you change settings in uYou,  it crashes the app.

Unable to reproduce...

https://streamable.com/7ygo7c

**Comment by JakeAi** [comment] 2023-06-23 19:02
> > If you change settings in uYou,  it crashes the app.
> 
> Unable to reproduce...
> 
> https://streamable.com/7ygo7c

I can do all of that. Except I changed the playback settings on WiFi to 1080 60fps. If I close app and restart, videos crash the app

**Comment by yodaluca23** [comment] 2023-06-23 19:35
> I can do all of that. Except I changed the playback settings on WiFi to 1080 60fps. If I close app and restart, videos crash the app

Happens when changing the cellular default too, probably a bug that someone on the team will need to fix, before updating to a newer version. Ether wait till then or just deal with it and don't use that setting...

**Comment by yodaluca23** [comment] 2023-06-24 21:30
> Just to chime in - ads are still blocked for me. Using the pre-release version, 18.15.1_3.0. OLED mode is working fine for me. (And all other functions are working too.)
> 
> 
> 
> iPhone 13 Pro iOS 17.0b2 - Signed w/ paid online signing service

Same thing for me exactly, it seems like only a few people were having the OLED problem.

iPhone 14 Pro

**Comment by Helguera** [comment] 2023-06-26 22:00
> not sure if this will work, but (so far) worked for me
> 
> go to A/B settings and disable "disableAfmaldfaCollection *" then close app right after to save settings!
> 
> 
> 
> search "afm" to find it more easily, so far no ads, will keep posted!

What is exactly A/B settings?

**Comment by leminlimez** [comment] 2023-06-28 02:14
same issue, i made sure the adblock toggle is on but it still shows me ads

**Comment by lequan81** [comment] 2023-06-28 12:23
> same issue, i made sure the adblock toggle is on but it still shows me ads

Have you tried mine release [above](https://github.com/qnblackcat/uYouPlus/issues/1160#issuecomment-1600991095)?

**Comment by Mukul1127** [comment] 2023-07-05 21:22
This is my build with the latest commits [https://github.com/Mukul1127/uYouPlus/releases/latest](https://github.com/Mukul1127/uYouPlus/releases/latest)

**Comment by Sevelayan** [comment] 2023-07-06 09:40
> Has some extra fixes

Does it block ads

**Comment by Honderdgramhesp** [comment] 2023-07-06 11:17
> This is my build with the latest commits https://github.com/Mukul1127/uYouPlus/releases/latest

The .ipa gives an error with Sideloadly! 
It says my device is'nt compatible. Did not have the issue with ''uYouPlus_18.14.1_3.0''

**Comment by johnomon** [comment] 2023-07-07 00:23
> > Has some extra fixes
> 
> Does it block ads

does it?

**Comment by Mukul1127** [comment] 2023-07-08 18:19
I haven't seen any

**Comment by Mukul1127** [comment] 2023-07-08 18:20
> > This is my build with the latest commits [Mukul1127/uYouPlus/releases/latest](https://github.com/Mukul1127/uYouPlus/releases/latest)
> 
> The .ipa gives an error with Sideloadly! It says my device is'nt compatible. Did not have the issue with ''uYouPlus_18.14.1_3.0''
> 
> EDIT: Iphone 13 did not work. Ipad 6th generation did work

I don't know what happened as there's no changes to the code, only one commit to fix building

**Comment by losh11** [comment] 2023-07-14 03:32
@Mukul1127 I believe it might be an xcode error, as sideloadly mentions something about app thinning not supported on iphone14,1, and lists many devices as supported.

**Comment by Honderdgramhesp** [comment] 2023-07-14 07:30
> > > This is my build with the latest commits [Mukul1127/uYouPlus/releases/latest](https://github.com/Mukul1127/uYouPlus/releases/latest)
> > 
> > 
> > The .ipa gives an error with Sideloadly! It says my device is'nt compatible. Did not have the issue with ''uYouPlus_18.14.1_3.0''
> > EDIT: Iphone 13 did not work. Ipad 6th generation did work
> 
> I don't know what happened as there's no changes to the code, only one commit to fix building I can say it works on the iPad 6th gen perfectly as that's what I'm using and where I decrypted the ipa.
> 
> EDIT: Seems like it's because iOS 16 has "jailbreak mitigation techniques" that makes it harder to dump apps.

I've tried it several times over to be sure it's not a random bug. But it still says the device is uncompatible.

**Comment by Mukul1127** [comment] 2023-07-14 15:19
You could maybe try AltStore or SideStore instead of Sideloadly as this could be a sideloadly error since its coming from sideloadly, not xcode while building

**Comment by Mukul1127** [comment] 2023-07-14 15:22
This is the only warning I found in the build logs
```
==> Warning: Building for iOS 9.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
```

**Comment by Honderdgramhesp** [comment] 2023-07-22 16:25
> This is the only warning I found in the build logs
> 
> ```
> ==> Warning: Building for iOS 9.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> ```
> 
> So this could be because your on iOS 14 and earlier with an A12+ device. From the website mentioned, this would require a downgrade to Xcode 11.7 to fix. Edit 3: I need help fixing the build, please contact me.

I'm here to answer all your questions regarding the bug on Iphone 13. 
I've tried to sideload the app with Altstore but it keeps on crashing..

**Comment by Mukul1127** [comment] 2023-07-29 00:35
> > This is the only warning I found in the build logs
> > ```
> > ==> Warning: Building for iOS 9.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So this could be because your on iOS 14 and earlier with an A12+ device. From the website mentioned, this would require a downgrade to Xcode 11.7 to fix. Edit 3: I need help fixing the build, please contact me.
> 
> I'm here to answer all your questions regarding the bug on Iphone 13. I've tried to sideload the app with Altstore but it keeps on crashing..
> 
> Edit: i've tried to sideload lequan81 build (uYouPlus version 18.15.1) with sideloadly and it worked perfect. No ads either Edit 2: I've reset my Ipad after I've sideloaded the Lequan81 build. Some of my favorite apps told me my Ipad was jailbroken or rooted so they stopped working. I don't have the problem what so ever with your build.

Thanks for the info, will be updating my build soon

**Comment by Practicalbutterfly5** [comment] 2023-07-29 12:11
uyou 3.0.1 update has fixed this issue, so hopefully we get plus updated as well

**Comment by Mukul1127** [comment] 2023-07-29 17:50
I'm updating it right now

**Closed** 2023-09-03 15:59 UTC
Labels: bug
