### ISSUE TITLE
[Bug] Downloads not working on iOS 16

### ISSUE THREAD

**Issue by Babyyoda777** [qnblackcat/uYouPlus#772] opened 2022-12-16 06:17 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...)
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_

### Describe the bug
Once download finishes, an error 200 pops up about moving the file from one location to another.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Simply try downloading a video or audio. Neither works.
### Crash log (if possible)
_(The crash log can be found in your device's Settings App > Privacy > Analytics & Improvements > Analytics Data > Youtube-xxx-xxx.ips)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
Yes latest release
### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

### Additional context: 
Doesn’t matter which download settings I use, same error on completion of download and using Webm only doesn’t show at all. Both downloads to Camera roll and uYou folder also fail individually.

**Comment by Babyyoda777** [comment] 2022-12-16 06:22
Here is a video

https://user-images.githubusercontent.com/80623330/208035597-7d225237-dda2-4d04-9189-a842a16c1140.mp4

**Comment by qnblackcat** [comment] 2022-12-16 06:23
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/238

**Closed by qnblackcat** 2022-12-16 06:23 UTC
Labels: bug
