### ISSUE TITLE
[Bug] Ads show in search results

### ISSUE THREAD

**Issue by synistr** [qnblackcat/uYouPlus#648] opened 2022-11-05 08:37 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.1
- Device model: 14 Pro Max
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): AltStore Direct IPA Sideload
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_: 17.42.7_2.1 (latest as of now)

### Describe the bug
I see ads in search results

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Search for something, the ad should show up at the top. I will attach a screenshot as well.
![149FAA11-EFCF-49E0-845A-4BCF665C2549](https://user-images.githubusercontent.com/94352963/200111191-d8518a1f-beb3-47bf-a889-5a3bf2c6d962.png)

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_Freshly installed, there haven‘t been any crashes yet

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_I am using the latest version.

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
Yup, because the official one doesn‘t block ads.
### Additional context: 
It worked in previous versions. Maybe this is happening because of the YouTube redesign?

**Comment by qnblackcat** [comment] 2022-11-05 08:54
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/81

**Closed by qnblackcat** 2022-11-05 08:54 UTC
Labels: bug
