### ISSUE TITLE
[Bug] Removing related vidoes is not working well

### ISSUE THREAD

**Issue by rock5684** [qnblackcat/uYouPlus#113] opened 2022-04-19 14:49 UTC
### Device info
- iOS/iPadOS version: ios 15.4.1
- Device model: iphone 13 pro
- Sideload tool (Ex: AltStore, Sideloadly...) altstore
- Version of uYouPlus:  17.09.1

### Describe the bug
when I turn off the option [related videos at the end the videos]
It removes related videos successfully, but other pop-ups are still alive.
a video title layout is still alive at the top of the screen when I watch video with full screen.

### How to reproduce the bug
turn off the option and watch video to the end with full screen. The option can't remove whole pop-ups for related vidoes

### Additional context: same issue - issue #54

**Comment by qnblackcat** [comment] 2022-04-19 15:14
Duplicate of #54

**Closed by qnblackcat** 2022-04-19 15:14 UTC
Labels: bug, duplicate
