### ISSUE TITLE
[Bug] Unable to login with Google Account

### ISSUE THREAD

**Issue by manhbi18112005** [qnblackcat/uYouPlus#332] opened 2022-08-03 15:41 UTC
### Device info
- iOS/iPadOS version: 15.6
- Device model: iPhone X
- Sideload tool: AltStore
- Version of uYouPlus: 17.26.2

### Describe the bug
New users are not able to login using Google Account.
![image](https://user-images.githubusercontent.com/69383979/182650284-3570b104-c00c-486c-8a6d-55c76f1d726c.png)

### How to reproduce the bug
Simply login using the traditional way.

### Crash log (if possible)
Currently not available

### Does the issue happen with the official YouTube from AppStore?
No

### Additional context: 
Please fix it quick I can not watch censored video 🤧

**Comment by arichorn** [comment] 2022-08-03 21:30
Check this out #319

**Comment by qnblackcat** [comment] 2022-08-03 23:17
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/319

**Closed by qnblackcat** 2022-08-03 23:17 UTC
Labels: bug
