### ISSUE TITLE
[Bug] The text of the uYou icon in the tab is strange!

### ISSUE THREAD

**Issue by iodes** [qnblackcat/uYouPlus#552] opened 2022-10-11 20:46 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0.3
- Device model: iPhone 14 Pro
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) : AltStore
- The specific version of uYouPlus: [v17.39.5-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.39.5-2.1)

### Describe the bug
When I launch the app, uYou text overlaps the uYou icon on bottom tab menu.
Click the uYou tab icon, then overlap will disappear.
But when I restart the app, the bug comes back!

### How to reproduce the bug
![IMG_0103](https://user-images.githubusercontent.com/1563800/195194213-61844a4b-4ae1-420c-864c-539ba11478c5.PNG)

### Are you using the newest version of uYouPlus? If not, why?
Yes

### Does the issue happen with the official YouTube from AppStore?
No

**Comment by arichorn** [comment] 2022-10-11 21:36
Same
![6CF11859-7AE2-4028-94F7-095F0B8BDBA0](https://user-images.githubusercontent.com/78001398/195202908-218af0c1-cb57-49ac-b5d8-c9dea7c70937.jpeg)
It just started happening recently

**Comment by arichorn** [comment] 2022-10-11 21:59
Let’s just say that this is caused by uYou itself. It hasn’t updated ever since YT 16.42.3 so it’s obvious that it’s gonna be breaking.

**Comment by level3tjg** [comment] 2022-10-12 20:36
I think this is caused by a botched A/B test, disabling `-[YTColdConfig mainAppCoreClientIosTransientVisualGlitchInPivotBarFix]` seems to fix it

**Comment by qnblackcat** [comment] 2022-10-13 04:07
> I think this is caused by a botched A/B test, disabling `-[YTColdConfig mainAppCoreClientIosTransientVisualGlitchInPivotBarFix]` seems to fix it

Yeap. This works!

**Comment by qnblackcat** [comment] 2022-10-15 16:06
fixed in [v17.40.5-2.1+](https://github.com/qnblackcat/uYouPlus/releases/latest)

**Comment by therealFoxster** [comment] 2023-03-08 08:30
Here's something interesting: if you set uYou to be the first tab (reorder), it doesn't happen anymore.

**Comment by qnblackcat** [comment] 2023-04-15 02:16
Fixed in uYou 3.0

**Comment by qnblackcat** [comment] 2023-04-17 06:53
Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)

**Closed by qnblackcat** 2023-04-17 06:53 UTC
Labels: bug, uYou
