### ISSUE TITLE
App keeps resetting settings

### ISSUE THREAD

**Issue by Dynasty-Dev** [qnblackcat/uYouPlus#388] opened 2022-08-18 00:35 UTC
At first everything works, I can sign in and login just fine and then a few hours later the app completely resets all uyouplus settings and prompts the do you want to enable returnyoutubedislike again. (Sometimes even 2 times). Any idea what causes this? It’s pretty random it’s not like it resets every time I launch the app more like every couple hours.

uYouPlus Build: Latest Release
Sideload method: Latest esign with UDID registrations gold
iOS: Tested on 16 Beta 6, Beta 5, iOS 15.6

Weird as I’ve used uYouPlus before and this didn’t happen

**Comment by qnblackcat** [comment] 2022-08-18 01:12
Duplicate of #335

**Closed by qnblackcat** 2022-08-18 01:12 UTC

**Comment by Dynasty-Dev** [comment] 2022-08-18 07:17
> Duplicate of #335

Ok, sorry about that. Uploading the app to appdb and using my certificate and provisoning files to appdb from udidregistrations worked for me

**Comment by Dynasty-Dev** [comment] 2022-08-18 07:21
> Duplicate of #335

By the way there is one small difference between these 2 opened issues and its that i dont get a youtube crashed popup. It just launches up normally and the return youtube dislikes menu pops up 2 times and all settings are reset.
