### ISSUE TITLE
[Bug]Hide download and other button option didn't work

### ISSUE THREAD

**Issue by Charlie102308** [qnblackcat/uYouPlus#145] opened 2022-05-07 16:14 UTC
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: iphone 13 pro max
- Sideload tool (Ex: AltStore, Sideloadly...):Altstore
- Version of uYouPlus: v.17.17.4-2.1

### Describe the bug
could not hid the download and other butto

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
I open the option for closing the download and create clip and short button and close restarting the app, but it didn't work.Even I close and reopen the option again and restarting the app, it still didn't work

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
![IMG_1259](https://user-images.githubusercontent.com/94617775/167262625-0e05868e-4c98-4ce8-8a92-fc266e8ba1ea.PNG)
![IMG_1260](https://user-images.githubusercontent.com/94617775/167262635-272d8a89-6b5c-40ae-8dce-bb4133f69cbe.PNG)

**Comment by qnblackcat** [comment] 2022-05-07 17:33
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/41

**Closed by qnblackcat** 2022-05-07 17:33 UTC
Labels: bug
