### ISSUE TITLE
Brightness toggle does not work 

### ISSUE THREAD

**Issue by romantra** [qnblackcat/uYouPlus#532] opened 2022-10-07 11:56 UTC
The brightness toggle does not work in iOS 16.0.2 on iPhone 14 pro Max 
![F7A285F4-CA34-4BE0-A50C-CA1C9399237E](https://user-images.githubusercontent.com/48365913/194547177-6851f54c-d019-41fc-91e2-86624fee520c.jpeg)

please help

**Comment by qnblackcat** [comment] 2022-10-07 16:16
Duplicate of #506

**Closed by qnblackcat** 2022-10-07 16:16 UTC
