### ISSUE TITLE
[Bug] App crashes while watching Shorts[Bug]

### ISSUE THREAD

**Issue by MrHegazyy** [qnblackcat/uYouPlus#382] opened 2022-08-17 03:22 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16 latest beta
- Device model: iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly...) altstore
- Version of uYouPlus: latest version 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore? No
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment] 2022-08-17 03:41
Duplicate of #253

**Closed by qnblackcat** 2022-08-17 03:41 UTC
Labels: bug
