### ISSUE TITLE
[Bug] Still can’t sign in normally in the new version

### ISSUE THREAD

**Issue by y0neh** [qnblackcat/uYouPlus#977] opened 2023-03-01 00:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3.1
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.08.1_2.3.1

### Describe the bug

When signing in, after email it shows “You can’t sign in to this app because Google can’t confirm that it’s safe”

### Steps to reproduce the issue

1. Open the latest version of the app
2. Log in
3. After email it shows this error

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by yodaluca23** [comment] 2023-03-01 00:59
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/972

<details>
I feel like this is going to be like the uYou update notification thing all over again....
</details>

**Comment by qnblackcat** [comment] 2023-03-01 02:56
Did you keep the original bundle ID of YouTube, which is com.google.ios.youtube ?

**Comment by garrytrytocode** [comment] 2023-03-01 03:17
Same as me, XR and cannot login.

**Comment by y0neh** [comment] 2023-03-01 11:34
> Did you keep the original bundle ID of YouTube, which is com.google.ios.youtube ?

Yes, all I did was update to this new version and I had been logged out, tried logging back in and got that error, old shortcuts method also doesn’t bypass it now sadly

**Closed** 2023-03-01 12:48 UTC
Labels: bug
