### ISSUE TITLE
[Bug] Notification Bell Icon crashes the app

### ISSUE THREAD

**Issue by Manujito** [qnblackcat/uYouPlus#185] opened 2022-06-03 18:34 UTC
When inside a channel, when tapping on the notification bell icon, the app crashes.

Tested on the past couple version via AltStore and Signulous. Same behavior.

**Comment by hero3210** [comment] 2022-06-04 01:21
Can confirm this happens.
I believe this is a uYou bug since it also happens with official YouTube app & uYou tweak on jailbroken devices.

**Comment by qnblackcat** [comment] 2022-06-04 05:54
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/83

**Closed by qnblackcat** 2022-06-04 05:54 UTC
Labels: bug
