### ISSUE TITLE
[Bug] uYou Buttons  & iSponsorblock colors missing

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#51] opened 2022-01-29 20:27 UTC
iOS 14.5, Sideloadly, latest uYou version

The uYou Buttons under the vid are gone (I checked uYou settings) and the iSponsorblock colors are gone too.

Never had this issue before. I just sideloaded the newest uYou version yesterday.

**Comment by qnblackcat** [comment] 2022-01-30 01:02
Duplicate of #48

**Closed by qnblackcat** 2022-01-30 01:02 UTC
Labels: bug, duplicate
