### ISSUE TITLE
[Bug] Dislike still visible

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#22] opened 2021-12-12 21:46 UTC
If you disable the dislike button under the video it's still visible.

Maybe you could add the functionality to hide the like buttons and the other buttons too?

**Comment by ErSpieltHD** [comment] 2021-12-12 21:46
I think it's because of the updates to the dislike button (they hid the counter etc) why this is no longer working

**Comment by qnblackcat** [comment] 2021-12-12 23:38
Duplicate of https://github.com/MiRO92/uYou-for-YouTube/issues/47

**Closed by qnblackcat** 2021-12-12 23:38 UTC
Labels: bug
