### ISSUE TITLE
[Bug] Not working change orientation button

### ISSUE THREAD

**Issue by Arhidj** [qnblackcat/uYouPlus#968] opened 2023-02-27 06:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS 16.4:
- 11 pro max:
- esign 
- 18.07.5:

### Describe the bug

At 17th version change orientation button is working. Now is broken. 

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by tevyisertyin** [comment] 2023-02-27 12:31
If you are referring to this button:
![5BBDC3F2-0560-4D7E-9362-E81A5F90FAA3](https://user-images.githubusercontent.com/104609012/221564375-77ad18b8-d673-4a38-848b-d2b1edcdf11b.jpeg)

I have already reported it as issue #900

**Comment by qnblackcat** [comment] 2023-02-28 02:48
Duplicate of #900

**Closed** 2023-02-28 02:48 UTC
Labels: bug
