### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ebug64** [qnblackcat/uYouPlus#322] opened 2022-07-29 02:12 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.5
- Device model: 13 Pro
- Sideload tool: AltStore
- Version of uYouPlus: v17.26.2

### Describe the bug

App crashes after scroll through 3 - 4 YouTube Shorts. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

After 3 - 4 Shorts the app crashes

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

No

### Additional context: 

Love the app <3

**Comment by qnblackcat** [comment] 2022-07-29 02:37
Duplicate of #253

**Closed by qnblackcat** 2022-07-29 02:37 UTC
Labels: bug
