### ISSUE TITLE
Failed Video Download Now The App Won't Launch

### ISSUE THREAD

**Issue by SmushyTaco** [qnblackcat/uYouPlus#1129] opened 2023-05-19 05:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.14.1-3.0

### Describe the bug

I tried downloading a YouTube video, the audio failed to download so it didn't save in my camera roll, I quit the YouTube app, and when I tried to launch it again, it just hangs on the loading screen. Restarting my phone didn't fix it.

### Steps to reproduce the issue

1. Relaunch the app after a failed video download.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment] 2023-05-19 08:24
Duplicate of #1107

**Closed by qnblackcat** 2023-05-19 08:24 UTC
Labels: bug
