### ISSUE TITLE
[Bug] Everything above 1080p is lagging

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#16] opened 2021-12-06 20:49 UTC
**Device info**
- iOS/iPadOS version: 15.2
- Device model: 12
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly

**Describe the bug**
- every video I try to watch with 2160p is lagging very badly

**How to Reproduce the bug**
_(Please attach videos or screenshots if possible)_

**Additional context**

**Comment by qnblackcat** [comment] 2021-12-07 02:59
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/6

**Closed by qnblackcat** 2021-12-07 02:59 UTC
