### ISSUE TITLE
[Bug] Offline download(Yt premium) not working

### ISSUE THREAD

**Issue by PARKasd** [qnblackcat/uYouPlus#610] opened 2022-10-26 00:46 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 15.6 RC, iPadOS 16.1 RC
- Device model: iPhone 13 Pro, Ipad Pro 11inch 2nd gen
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) iphone uses Altstore and signum, ipad uses Signulous
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_17.41.2

### Describe the bug
When using altstore, feature works pretty well. However, when I try to install the app with some sevices, I can't.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Just press offline download
### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
Nope
### Additional context: 
Just telling some information that if people trying to install apps by paid service, It may not work.

**Comment by qnblackcat** [comment] 2022-10-26 02:22
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/327

**Closed by qnblackcat** 2022-10-26 02:22 UTC
Labels: bug
