### ISSUE TITLE
[Bug] Ad when searching specific word

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#718] opened 2022-11-28 22:07 UTC
Device info

iOS/iPadOS version: 16.2
Device model: 14 Pro
Sideload tool: Sideloadly
The specific version of uYouPlus: v17.43.1-2.1

Describe the bug:

When searching for a specific word and sometimes randomly the same ad pops up. It doesn't matter if I disable/enable Ads in uYou Settings.

![image](https://user-images.githubusercontent.com/40891294/204391286-328e439d-2b01-4556-bd91-700c6fcd4af5.jpeg)

**Comment by arichorn** [comment] 2022-11-28 22:29
You don’t have to ping me, uYouPlus & uYouPlusExtra are but the same except Extra just adds some small changes & improvements. But no fixes.

**Comment by qnblackcat** [comment] 2022-11-29 00:24
Duplicate of #81

**Closed by qnblackcat** 2022-11-29 00:24 UTC
Labels: bug
