### ISSUE TITLE
[enhancement ] option to remove irrelevant search results

### ISSUE THREAD

**Issue by superfreeman1989** [qnblackcat/uYouPlus#699] opened 2022-11-21 02:15 UTC
Youtube's search results have been littered with more and more irrelevant results, such as "latest from..." "people also watched" "for you" "previously watched" "from related searches". There are scripts like [this](https://greasyfork.org/en/scripts/454513-youtube-search-results-cleaner) that can clean them up. Would it be possible to implement it as an option? 
Thanks

**Comment by qnblackcat** [comment] 2022-11-21 03:56
Duplicate of #81

**Closed by qnblackcat** 2022-11-21 03:56 UTC

**Comment by superfreeman1989** [comment] 2022-11-21 21:37
> Duplicate of #81

Hi, #81 seems to be about ads in search results. This is about non-ad irrelevant results.

**Comment by LeonDerDr** [comment] 2022-12-16 22:01
I agree. This is a must @qnblackcat
