### ISSUE TITLE
[Bug] Crash on Shorts tab

### ISSUE THREAD

**Issue by jeffzyliu** [qnblackcat/uYouPlus#370] opened 2022-08-12 08:03 UTC
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 15.6
- Device model: iPhone X
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore 
- Version of uYouPlus: v17.30.3-2.1

### Describe the bug

App crashes when scrolling through shorts tab

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

Open shorts tab, scroll down. Usually 3 shorts down, the app immediately crashes.

This crash also happens when I open a suggested short through the home feed, and scroll down 3 shorts.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

Unsure, I don't have it installed.

### Additional context:

**Comment by qnblackcat** [comment] 2022-08-12 08:08
Duplicate of #253

**Closed by qnblackcat** 2022-08-12 08:08 UTC
Labels: bug
