### ISSUE TITLE
[Bug] Can’t sign in error has returned

### ISSUE THREAD

**Issue by karmaisacat** [qnblackcat/uYouPlus#992] opened 2023-03-05 14:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: M1 11" iPad Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Scarlet
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.08.1_2.3.1 2

### Describe the bug

Getting the "Couldn't sign you in, You can't sign in to this app because Google can't confirm that it's safe." error when signing into my Google account. 
![IMG_0380](https://user-images.githubusercontent.com/123435581/222966442-a29912dc-d407-45ae-b321-9a2738895c6c.jpeg)

### Steps to reproduce the issue

1. Download uYouPlus
2. Sign in
3. Get error

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment] 2023-03-05 14:29
Duplicate of #990

**Closed by qnblackcat** 2023-03-05 14:29 UTC
Labels: bug
