### ISSUE TITLE
Keyboard reverted back to dark theme instead of OLED

### ISSUE THREAD

**Issue by AdiA105** [qnblackcat/uYouPlus#122] opened 2022-04-22 17:17 UTC
![image](https://user-images.githubusercontent.com/104014894/164763130-5c0d287d-dc28-49a5-856a-0749ceaff0b1.png)

**Comment by qnblackcat** [comment] 2022-04-22 17:55
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/114

**Closed by qnblackcat** 2022-04-22 17:55 UTC
Labels: bug

**Comment by AdiA105** [comment] 2022-04-22 18:05
This is not a duplicate. The keyboard has Reverted back to dark theme. This means that in a previous version of the app ([this](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/EWrA2cb6QBhJkAv_wyMZD90BxCDdF0YOI_cNiO7StzgATQ?download=1) one) the keyboard looked as intended(minus the prediction bar and bottom bar). This is no longer the case.

**Comment by qnblackcat** [comment] 2022-04-22 18:20
Sorry, I don’t know how to fully color the KB. Better leave it's like default.

**Comment by qnblackcat** [comment] 2022-04-22 18:22
```
%hook UIKeyboardLayoutStar
-(void)layoutSubviews {
self.backgroundColor = [UIColor blackColor];
%orig; 
}
%end
```
Here is the code If you want to re-add the kb color
