### ISSUE TITLE
[Bug] Crashing on launch after sideloading app on iOS 16

### ISSUE THREAD

**Issue by stectr** [qnblackcat/uYouPlus#192] opened 2022-06-07 08:24 UTC
### Device info
- iOS/iPadOS version: iOS 16
- Device model: iPhone 13
- Sideload tool (Ex: AltStore, Sideloadly...) Signum
- Version of uYouPlus: 17.22.3_2.1, 17.21.3_2.1, 17.17.4_2.1

### Describe the bug
App crashes on launch after freshly sideloading it.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Sideload app and launch. 

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
I previously had 17.17.4_2.1 on my device and then I updated to iOS 16 and it was still working (after turning on developer mode of course). Then I deleted the app to install a the newest version and it crashes on launch so I try restarting my device to see if that works, which it doesn't. I then went back to 17.17.4_2.1 because that should work if it worked before deletion, but alas that does not work either.

**Comment by qnblackcat** [comment] 2022-06-07 08:29
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/190

**Closed by qnblackcat** 2022-06-07 08:29 UTC
Labels: bug

**Comment by stectr** [comment] 2022-06-07 08:36
This is a different issue from #190. Their issue was simply not enabling developer mode but I have developer mode on and none of the versions work

**Comment by arichorn** [comment] 2022-06-07 08:44
Oh. I’m pretty sure uYou is using an iOS 15 SDK, idk fully though, but I guess there is a iOS 16 uYou issue

**Comment by stectr** [comment] 2022-06-07 08:54
It's strange because the app worked fine before I deleted and reinstalled it.

**Comment by arichorn** [comment] 2022-06-07 17:42
Now I’m scared to remove the app now
