### ISSUE TITLE
[Questions] Is the ad result in search on purpose or it’s a bug waiting to be squashed?

### ISSUE THREAD

**Issue by AbsurdIdealist** [qnblackcat/uYouPlus#344] opened 2022-08-05 13:48 UTC
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

**Comment by qnblackcat** [comment] 2022-08-05 15:15
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/81

**Closed by qnblackcat** 2022-08-05 15:15 UTC
Labels: question
